import type { CampaignActionId, CampaignActionV2 } from './types';

const risk = (
  backlash: number,
  legal: number,
  media: number,
  scandal: number,
  counterMobilization: number,
  internalFaction = 0.05,
  coalitionToxicity = 0.05,
): CampaignActionV2['risks'] => ({
  backlash,
  legal,
  media,
  scandal,
  counterMobilization,
  internalFaction,
  coalitionToxicity,
});

export const campaignActionsV2: CampaignActionV2[] = [
  {
    id: 'regionalMeeting',
    name: 'Regionalni setkani',
    description: 'Otevrene setkani s lokalnimi organizatory a zastupci komunit v syntetickem hernim regionu.',
    category: 'field',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.8,
    staffCost: 1,
    leaderTimeCost: 0.2,
    fatigueCost: 0.04,
    cooldownWeeks: 1,
    target: { scope: 'region', required: ['region'] },
    effects: {
      regionOrganizationShift: 0.07,
      reputationShift: { authenticity: 0.018, trust: 0.008 },
      issueSalienceShift: { housing: 0.4, transport: 0.3 },
      latentWidthShift: { culture: 0.008 },
    },
    risks: risk(0.04, 0, 0.04, 0.02, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Lokalni organizace a autenticita', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'republicTour',
    name: 'Republikove turne',
    description: 'Narocny tyden viditelnych zastavek v nekolika regionech, ktery testuje kapacitu stabni logistiky.',
    category: 'field',
    legality: 'clean',
    ethicalRisk: 0.03,
    cost: 2.1,
    staffCost: 2,
    leaderTimeCost: 0.75,
    fatigueCost: 0.16,
    cooldownWeeks: 2,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.025,
      regionOrganizationShift: 0.025,
      reputationShift: { authenticity: 0.012, trust: 0.012 },
      latentWidthShift: { authority: 0.01, culture: 0.01 },
    },
    risks: risk(0.08, 0, 0.08, 0.03, 0.06),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Viditelnost a sit v regionech', riskLabel: 'Unava lidra' },
  },
  {
    id: 'townHall',
    name: 'Verejna debata',
    description: 'Moderovane setkani s dotazy verejnosti, ktere zvedne citelnost, ale muze odhalit slaba mista programu.',
    category: 'field',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.9,
    staffCost: 1,
    leaderTimeCost: 0.35,
    fatigueCost: 0.07,
    target: { scope: 'region', required: ['region'] },
    effects: {
      regionOrganizationShift: 0.045,
      issueSalienceShift: { antiCorruption: 0.4, housing: 0.4 },
      reputationShift: { authenticity: 0.016, competence: 0.006 },
      mediaVulnerabilityShift: 0.01,
    },
    risks: risk(0.06, 0, 0.08, 0.03, 0.05),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Duvihodnost v terenu', riskLabel: 'Nizke az stredni riziko' },
  },
  {
    id: 'schoolVisit',
    name: 'Navsteva skoly',
    description: 'Verejna navsteva vzdelavaci instituce zamereny na programovou citelnost u mladsich syntetickych segmentu.',
    category: 'field',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.6,
    staffCost: 1,
    leaderTimeCost: 0.45,
    fatigueCost: 0.08,
    target: { scope: 'region', required: ['region'] },
    effects: {
      issueSalienceShift: { education: 0.7, sameSexMarriage: 0.5, cannabis: 0.3 },
      framingChange: { sameSexMarriage: 'noCultureWar' },
      reputationShift: { authenticity: 0.018 },
      latentWidthShift: { culture: 0.015 },
    },
    risks: risk(0.07, 0, 0.1, 0.03, 0.05),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Vzdelani a kulturni citelnost', riskLabel: 'Stredni medialni tlak' },
  },
  {
    id: 'factoryVisit',
    name: 'Navsteva vyroby',
    description: 'Setkani s pracovisti a odbory ve fiktivnim regionu, ktere posiluje prumyslovou linku programu.',
    category: 'field',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.9,
    staffCost: 1,
    leaderTimeCost: 0.4,
    fatigueCost: 0.08,
    target: { scope: 'region', required: ['region'] },
    effects: {
      regionOrganizationShift: 0.05,
      issueSalienceShift: { industry: 0.8, energyPrices: 0.5 },
      framingChange: { energyPrices: 'cheapEnergy' },
      reputationShift: { competence: 0.012, authenticity: 0.01 },
      latentCenterShift: { econ: -0.01 },
    },
    risks: risk(0.06, 0, 0.06, 0.02, 0.04),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Prumysl, energie a organizace', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'doorToDoor',
    name: 'Door-to-door',
    description: 'Dobrovolnicka pozemni kampan v regionu; efekt jde pres organizaci a znalost lokalniho terenu.',
    category: 'organization',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.7,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.02,
    target: { scope: 'region', required: ['region'] },
    effects: {
      regionOrganizationShift: 0.09,
      turnoutModifier: { scope: 'region', amount: 0.012 },
      reputationShift: { authenticity: 0.006 },
    },
    risks: risk(0.04, 0, 0.02, 0.02, 0.04),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Organizace a priprava turnout vrstvy', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'billboardCampaign',
    name: 'Billboardova kampan',
    description: 'Viditelna placena komunikace, ktera zvysi dosah bez presneho primeho prepoctu na podporu.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.03,
    cost: 1.7,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    cooldownWeeks: 2,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.018,
      mediaVulnerabilityShift: 0.01,
      issueSalienceShift: { housing: 0.3, antiCorruption: 0.3 },
    },
    risks: risk(0.07, 0, 0.08, 0.03, 0.06),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Dosah a salience sdeleni', riskLabel: 'Nizke az stredni riziko' },
  },
  {
    id: 'tvDebate',
    name: 'TV debata',
    description: 'Vysoce sledovana debata s velkym rozptylem vysledku podle unavy lidra a koherence programu.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.03,
    cost: 1.3,
    staffCost: 1,
    leaderTimeCost: 0.65,
    fatigueCost: 0.13,
    cooldownWeeks: 2,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.035,
      reputationShift: { competence: 0.014 },
      mediaVulnerabilityShift: 0.035,
      issueSalienceShift: { antiCorruption: 0.3, housing: 0.3 },
    },
    risks: risk(0.12, 0, 0.18, 0.08, 0.1),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Velky dosah, vysoka variance', riskLabel: 'Vyssi medialni riziko' },
  },
  {
    id: 'controlledInterview',
    name: 'Kontrolovany rozhovor',
    description: 'Predvidatelny rozhovor s omezenym dosahem, vhodny pro kompetencni a reputacni linku.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.7,
    staffCost: 1,
    leaderTimeCost: 0.35,
    fatigueCost: 0.06,
    target: { scope: 'mediaOutlet' },
    effects: {
      fieldAmplitude: 0.016,
      reputationShift: { competence: 0.016, trust: 0.006 },
      mediaVulnerabilityShift: 0.005,
    },
    risks: risk(0.05, 0, 0.06, 0.02, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Kompetence a dosah', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'regionalMediaAppearance',
    name: 'Regionalni media',
    description: 'Vystup v regionalnich mediich, ktery propojuje lokalni agendu s organizaci strany.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.55,
    staffCost: 1,
    leaderTimeCost: 0.25,
    fatigueCost: 0.04,
    target: { scope: 'region', required: ['region'] },
    effects: {
      fieldAmplitude: 0.01,
      regionOrganizationShift: 0.035,
      issueSalienceShift: { transport: 0.5, healthcare: 0.4 },
      reputationShift: { trust: 0.006 },
    },
    risks: risk(0.04, 0, 0.05, 0.02, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Regionalni agenda a sit', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'podcastInterview',
    name: 'Podcastovy rozhovor',
    description: 'Dlouhy format pro vysvetleni priorit, s mensim dosahem a vyssim vlivem na citelnost.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.45,
    staffCost: 1,
    leaderTimeCost: 0.3,
    fatigueCost: 0.04,
    target: { scope: 'national' },
    effects: {
      reputationShift: { competence: 0.01, consistency: 0.01 },
      issueSalienceShift: { antiCorruption: 0.4, civilServiceReform: 0.3 },
      informationQualityShift: 0.015,
    },
    risks: risk(0.04, 0, 0.04, 0.02, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Citelnost a konzistence', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'pressConference',
    name: 'Tiskova konference',
    description: 'Formalni medialni vystup, ktery zvysuje institucionlni citelnost a soucasne pozornost novinaru.',
    category: 'media',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.6,
    staffCost: 1,
    leaderTimeCost: 0.25,
    fatigueCost: 0.04,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.012,
      reputationShift: { competence: 0.012 },
      mediaVulnerabilityShift: 0.018,
      issueSalienceShift: { antiCorruption: 0.4 },
    },
    risks: risk(0.07, 0, 0.1, 0.04, 0.05),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Formalni dosah a agenda', riskLabel: 'Stredni medialni tlak' },
  },
  {
    id: 'policyPackage',
    name: 'Programovy balik',
    description: 'Sada tematickych zavazku, ktera meni issue vrstvu, salienci a 8D pozici strany.',
    category: 'program',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 1,
    staffCost: 1,
    leaderTimeCost: 0.25,
    fatigueCost: 0.03,
    cooldownWeeks: 1,
    target: { scope: 'issue', optional: ['issue'] },
    effects: {
      reputationShift: { competence: 0.026, consistency: 0.012 },
      issueSalienceShift: { housing: 0.7, energyPrices: 0.5, antiCorruption: 0.4 },
      issuePositionShift: { housing: 0.1 },
      latentWidthShift: { econ: 0.018 },
    },
    risks: risk(0.05, 0, 0.06, 0.02, 0.05, 0.08),
    preview: { visibleToPlayer: true, precisionRequired: 'focusGroup', shortEffectLabel: 'Issue salience, kompetence a 8D posun', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'policyPaper',
    name: 'Odborny podklad',
    description: 'Detailni material pro policy vrstvu; zvysuje kompetenci a konzistenci bez primeho popularitniho boostu.',
    category: 'program',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.65,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    target: { scope: 'issue', optional: ['issue'] },
    effects: {
      reputationShift: { competence: 0.018, consistency: 0.012 },
      issueSalienceShift: { civilServiceReform: 0.4, antiCorruption: 0.3 },
      informationQualityShift: 0.02,
    },
    risks: risk(0.03, 0, 0.03, 0.01, 0.02, 0.05),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Kompetence a programova citelnost', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'budgetedProposal',
    name: 'Rozpoctovane opatreni',
    description: 'Programovy navrh s financnim ramcem, ktery posiluje kompetenci a omezuje medialni zranitelnost.',
    category: 'program',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.9,
    staffCost: 1,
    leaderTimeCost: 0.15,
    fatigueCost: 0.02,
    target: { scope: 'issue', optional: ['issue'] },
    effects: {
      reputationShift: { competence: 0.028, trust: 0.006 },
      issueSalienceShift: { taxes: 0.4, pensions: 0.4 },
      mediaVulnerabilityShift: -0.02,
    },
    risks: risk(0.04, 0, 0.04, 0.01, 0.03, 0.05),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Kompetence a mensi zranitelnost', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'parliamentSpeech',
    name: 'Snemovni projev',
    description: 'Institucionalni vystup, ktery posiluje kompetenci a vazbu na protikorupcni nebo spravni temata.',
    category: 'parliament',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.5,
    staffCost: 1,
    leaderTimeCost: 0.35,
    fatigueCost: 0.05,
    target: { scope: 'national' },
    effects: {
      reputationShift: { competence: 0.024, trust: 0.01 },
      issueSalienceShift: { antiCorruption: 0.6, civilServiceReform: 0.5 },
      framingChange: { antiCorruption: 'cleanState' },
    },
    risks: risk(0.04, 0, 0.05, 0.02, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Institucionalni respekt', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'interpellation',
    name: 'Interpelace',
    description: 'Parlamentni tlak na vladu, ktery zvedne salienci tematu a mirne zhorsi koalicni atmosferu.',
    category: 'parliament',
    legality: 'clean',
    ethicalRisk: 0.03,
    cost: 0.35,
    staffCost: 1,
    leaderTimeCost: 0.25,
    fatigueCost: 0.04,
    target: { scope: 'issue', optional: ['issue'] },
    effects: {
      issueSalienceShift: { housing: 0.4, healthcare: 0.4 },
      reputationShift: { competence: 0.012, controversy: 0.006 },
      coalitionRelationShift: -0.02,
    },
    risks: risk(0.06, 0, 0.07, 0.02, 0.05, 0.04, 0.08),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Tematicky tlak na soupereni', riskLabel: 'Nizke az stredni riziko' },
  },
  {
    id: 'shadowCabinetBriefing',
    name: 'Briefing stinoveho tymu',
    description: 'Koordinace expertu a mluvci strany, ktera zlepsuje citelnost a snizuje medialni chyby.',
    category: 'parliament',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.75,
    staffCost: 1,
    leaderTimeCost: 0.1,
    fatigueCost: 0.02,
    target: { scope: 'national' },
    effects: {
      reputationShift: { competence: 0.018, consistency: 0.018 },
      informationQualityShift: 0.025,
      mediaVulnerabilityShift: -0.025,
    },
    risks: risk(0.03, 0, 0.03, 0.01, 0.02, 0.04),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Koordinace a mensi medialni riziko', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'internalTrackingPoll',
    name: 'Interni tracking',
    description: 'Merici nastroj pro zpresneni odhadu. Neposiluje podporu primo.',
    category: 'analytics',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.5,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0,
    target: { scope: 'region', optional: ['region'] },
    effects: {
      informationQualityShift: 0.16,
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.01),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Presnejsi odhady bez prime podpory', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'focusGroup',
    name: 'Focus group',
    description: 'Kvalitativni test barier a jazyka programu v syntetickem segmentu. Nepredstavuje navod k presvedcovani.',
    category: 'analytics',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.7,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    target: { scope: 'segment', optional: ['segment'] },
    effects: {
      informationQualityShift: 0.1,
      reputationShift: { consistency: 0.008 },
      mediaVulnerabilityShift: -0.02,
      framingChange: { housing: 'cleanState' },
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.01),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Lepsi jazyk a presnost odhadu', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'messageTesting',
    name: 'Test sdeleni',
    description: 'Bezpecny interni test citelnosti sdeleni; zlepsuje predikci a snizuje riziko spatneho ramovani.',
    category: 'analytics',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.9,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    target: { scope: 'national' },
    effects: {
      informationQualityShift: 0.12,
      reputationShift: { controversy: -0.01 },
      mediaVulnerabilityShift: -0.03,
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.01),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Presnejsi preview a mensi riziko', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'regionalAnalysis',
    name: 'Regionalni analyza',
    description: 'Analyticka priprava na regionalni rozhodnuti; pripravuje budouci turnout a organizacni model.',
    category: 'analytics',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.55,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0,
    target: { scope: 'region', required: ['region'] },
    effects: {
      informationQualityShift: 0.08,
      regionOrganizationShift: 0.015,
      turnoutModifier: { scope: 'region', amount: 0.004 },
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.01),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Presnejsi region a priprava turnout vrstvy', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'volunteerRecruitment',
    name: 'Nabor dobrovolniku',
    description: 'Organizacni investice do terenni kapacity a budouci lokalni prace.',
    category: 'organization',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.8,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.02,
    cooldownWeeks: 1,
    target: { scope: 'region', required: ['region'] },
    effects: {
      regionOrganizationShift: 0.11,
      turnoutModifier: { scope: 'region', amount: 0.008 },
      reputationShift: { authenticity: 0.006 },
    },
    risks: risk(0.03, 0, 0.02, 0.01, 0.02),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Kapacita v regionu', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'candidateTraining',
    name: 'Trenink kandidatu',
    description: 'Priprava regionalnich kandidatu na media a verejne akce, ktera snizuje chyby mimo centrum.',
    category: 'organization',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.75,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    target: { scope: 'region', optional: ['region'] },
    effects: {
      regionOrganizationShift: 0.06,
      reputationShift: { competence: 0.01, consistency: 0.008 },
      mediaVulnerabilityShift: -0.02,
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.02),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Regionalni kompetence', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'leaderMediaTraining',
    name: 'Medialni priprava lidra',
    description: 'Priprava lidra na rizikove formaty, ktera snizuje medialni zranitelnost za cenu casu.',
    category: 'organization',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.8,
    staffCost: 1,
    leaderTimeCost: 0.2,
    fatigueCost: 0.03,
    cooldownWeeks: 2,
    target: { scope: 'leader' },
    effects: {
      reputationShift: { competence: 0.012, consistency: 0.01 },
      mediaVulnerabilityShift: -0.04,
      informationQualityShift: 0.02,
    },
    risks: risk(0.02, 0, 0.02, 0.01, 0.01),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Mensi riziko v mediich', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'coalitionSignal',
    name: 'Koalicni signal',
    description: 'Verejny umirneny signal mozne spoluprace, ktery zvysuje kompatibilitu, ale muze drrazdit cast jadra.',
    category: 'coalition',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 0.4,
    staffCost: 1,
    leaderTimeCost: 0.1,
    fatigueCost: 0.01,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      coalitionRelationShift: 0.06,
      reputationShift: { trust: 0.008, controversy: -0.004 },
    },
    risks: risk(0.04, 0, 0.04, 0.01, 0.04, 0.08, 0),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Koalicni kompatibilita', riskLabel: 'Nizke riziko u jadra' },
  },
  {
    id: 'nonAttackPact',
    name: 'Neutocna dohoda',
    description: 'Diskretni politicky signal bez detailu vyjednavani; snizuje konflikt s vybranou stranou.',
    category: 'coalition',
    legality: 'clean',
    ethicalRisk: 0.03,
    cost: 0.35,
    staffCost: 1,
    leaderTimeCost: 0.1,
    fatigueCost: 0.01,
    cooldownWeeks: 2,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      coalitionRelationShift: 0.08,
      reputationShift: { consistency: -0.004, trust: 0.004 },
      mediaVulnerabilityShift: 0.006,
    },
    risks: risk(0.05, 0, 0.06, 0.02, 0.05, 0.08, 0),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Mensi konflikt, mozna kritika jadra', riskLabel: 'Nizke az stredni riziko' },
  },
  {
    id: 'gotvOperation',
    name: 'GOTV operace',
    description: 'Legalni mobilizacni priprava vlastnich sympatizantu ve fiktivnim modelu turnout vrstvy.',
    category: 'turnout',
    legality: 'clean',
    ethicalRisk: 0.02,
    cost: 1.1,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.02,
    cooldownWeeks: 1,
    target: { scope: 'region', optional: ['region'] },
    effects: {
      turnoutModifier: { scope: 'region', amount: 0.018 },
      regionOrganizationShift: 0.035,
      reputationShift: { authenticity: 0.004 },
    },
    risks: risk(0.04, 0, 0.03, 0.01, 0.04),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Priprava oddelene turnout vrstvy', riskLabel: 'Nizke riziko' },
  },
  {
    id: 'crisisApology',
    name: 'Krizova omluva',
    description: 'Transparentni reakce na chybu, ktera kratkodobe zviditelni problem, ale snizuje reputacni skodu.',
    category: 'crisis',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.35,
    staffCost: 1,
    leaderTimeCost: 0.2,
    fatigueCost: 0.03,
    target: { scope: 'national' },
    effects: {
      reputationShift: { integrity: 0.025, trust: 0.018, controversy: -0.025 },
      scandalRiskShift: -0.06,
      mediaVulnerabilityShift: -0.02,
    },
    risks: risk(0.05, 0, 0.08, 0.03, 0.03),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Snizeni skandalniho rizika', riskLabel: 'Kratkodoby medialni tlak' },
  },
  {
    id: 'transparentAudit',
    name: 'Transparentni audit',
    description: 'Dobrovolne zpristupneni financni a organizacni kontroly v hernim modelu.',
    category: 'crisis',
    legality: 'clean',
    ethicalRisk: 0.01,
    cost: 0.55,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.01,
    cooldownWeeks: 3,
    target: { scope: 'national' },
    effects: {
      reputationShift: { integrity: 0.06, trust: 0.012, controversy: -0.02 },
      scandalRiskShift: -0.08,
      legalExposureShift: -0.06,
      mediaVulnerabilityShift: -0.015,
    },
    risks: risk(0.03, 0, 0.04, 0.01, 0.02),
    preview: { visibleToPlayer: true, precisionRequired: 'none', shortEffectLabel: 'Integrita a nizsi expozice', riskLabel: 'Velmi nizke riziko' },
  },
  {
    id: 'hardNegativeCampaign',
    name: 'Tvrda negativni kampan',
    description: 'Agresivni, ale legalni kritika soupere modelovana abstraktne pres reputacni a koalicni nasledky.',
    category: 'negative',
    legality: 'clean',
    ethicalRisk: 0.28,
    cost: 1.1,
    staffCost: 1,
    leaderTimeCost: 0.15,
    fatigueCost: 0.03,
    cooldownWeeks: 2,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      fieldAmplitude: 0.012,
      reputationShift: { controversy: 0.05, authenticity: -0.012, trust: -0.006 },
      mediaVulnerabilityShift: 0.04,
      scandalRiskShift: 0.025,
      coalitionRelationShift: -0.08,
      counterMobilizationRiskShift: 0.04,
    },
    risks: risk(0.28, 0.02, 0.26, 0.14, 0.22, 0.08, 0.18),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Kratkodoby tlak, reputacni cena', riskLabel: 'Vysoke backlash riziko' },
  },
  {
    id: 'oppositionResearch',
    name: 'Opozicni research',
    description: 'Legalni analyza verejnych informaci o souperi; ve hre zvysuje presnost a riziko konfliktu.',
    category: 'negative',
    legality: 'clean',
    ethicalRisk: 0.12,
    cost: 0.8,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.01,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      informationQualityShift: 0.08,
      mediaVulnerabilityShift: 0.015,
      coalitionRelationShift: -0.035,
      reputationShift: { controversy: 0.01 },
    },
    risks: risk(0.1, 0.01, 0.1, 0.05, 0.08, 0.04, 0.08),
    preview: { visibleToPlayer: true, precisionRequired: 'poll', shortEffectLabel: 'Informace a konflikt', riskLabel: 'Stredni politicke riziko' },
  },
  {
    id: 'allyEcosystemAmplification',
    name: 'Amplifikace spojencu',
    description: 'Abstraktni model podpory od sympatizujicich akteru; nejde o instrukce k koordinaci v realnem svete.',
    category: 'ally',
    legality: 'gray',
    ethicalRisk: 0.3,
    cost: 0.6,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.01,
    cooldownWeeks: 2,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.018,
      reputationShift: { controversy: 0.018, integrity: -0.012 },
      mediaVulnerabilityShift: 0.035,
      legalExposureShift: 0.025,
      scandalRiskShift: 0.035,
    },
    risks: risk(0.18, 0.12, 0.2, 0.14, 0.12, 0.05, 0.12),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Vetsi dosah za cenu kontroly', riskLabel: 'Seda zona' },
  },
  {
    id: 'unofficialSupportNetwork',
    name: 'Neoficialni podporna sit',
    description: 'Seda zona modelovana pouze abstraktne: zvysuje dosah a soucasne expozici, toxicitu a skandalni riziko.',
    category: 'grayZone',
    legality: 'gray',
    ethicalRisk: 0.45,
    cost: 0.45,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.02,
    cooldownWeeks: 3,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.022,
      reputationShift: { integrity: -0.025, controversy: 0.03 },
      mediaVulnerabilityShift: 0.05,
      legalExposureShift: 0.05,
      scandalRiskShift: 0.07,
      coalitionRelationShift: -0.05,
    },
    risks: risk(0.25, 0.22, 0.3, 0.25, 0.16, 0.08, 0.2),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Dosah s vyraznou expozici', riskLabel: 'Vysoka seda zona' },
  },
  {
    id: 'conflictCommunityManagement',
    name: 'Rizikova sprava komunity',
    description: 'Abstraktni moderacni a konfliktni zasah v online komunite s backlash a koalicnimi nasledky.',
    category: 'grayZone',
    legality: 'gray',
    ethicalRisk: 0.34,
    cost: 0.5,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.02,
    target: { scope: 'segment', optional: ['segment'] },
    effects: {
      informationQualityShift: 0.035,
      reputationShift: { controversy: 0.026, trust: -0.012 },
      mediaVulnerabilityShift: 0.045,
      counterMobilizationRiskShift: 0.04,
      coalitionRelationShift: -0.03,
    },
    risks: risk(0.22, 0.08, 0.24, 0.14, 0.2, 0.08, 0.12),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Segmentovy tlak a backlash', riskLabel: 'Seda zona' },
  },
  {
    id: 'controversialMicrotargeting',
    name: 'Kontroverzni mikrocileni',
    description: 'Abstraktni herni mechanika presnosti a backlash rizika; neobsahuje postupy realneho cileni.',
    category: 'grayZone',
    legality: 'gray',
    ethicalRisk: 0.52,
    cost: 1,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.02,
    cooldownWeeks: 2,
    target: { scope: 'segment', optional: ['segment'] },
    effects: {
      informationQualityShift: 0.07,
      fieldAmplitude: 0.012,
      reputationShift: { integrity: -0.03, controversy: 0.04 },
      mediaVulnerabilityShift: 0.06,
      legalExposureShift: 0.055,
      counterMobilizationRiskShift: 0.05,
    },
    risks: risk(0.3, 0.2, 0.28, 0.2, 0.24, 0.06, 0.16),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Vyssi presnost, vysoka eticka cena', riskLabel: 'Seda zona s expozici' },
  },
  {
    id: 'demobilizingNegativeNarrative',
    name: 'Demobilizacni negativni narativ',
    description: 'Abstraktni negativni taktika s vysokou etickou cenou, modelovana pres backlash a protimobilizaci.',
    category: 'grayZone',
    legality: 'gray',
    ethicalRisk: 0.62,
    cost: 0.9,
    staffCost: 1,
    leaderTimeCost: 0.05,
    fatigueCost: 0.03,
    cooldownWeeks: 3,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      demobilizationModifier: { scope: 'opponent', amount: -0.01 },
      reputationShift: { integrity: -0.045, controversy: 0.055, trust: -0.02 },
      mediaVulnerabilityShift: 0.07,
      legalExposureShift: 0.06,
      scandalRiskShift: 0.08,
      coalitionRelationShift: -0.08,
      counterMobilizationRiskShift: 0.07,
    },
    risks: risk(0.38, 0.22, 0.34, 0.26, 0.32, 0.12, 0.24),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Nedominantni, vysoko rizikova demobilizace', riskLabel: 'Vysoke eticke a politicke riziko' },
  },
  {
    id: 'fabricatedScandalAbstract',
    name: 'Abstraktni vykonstruovana kauza',
    description: 'Ilegalni black-ops mechanika pouze pro simulaci rizik: kratkodoby tlak je vykoupen pravni expozici a ztratou integrity.',
    category: 'blackOps',
    legality: 'illegal',
    ethicalRisk: 0.95,
    cost: 0.4,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.04,
    cooldownWeeks: 5,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      fieldAmplitude: 0.006,
      reputationShift: { integrity: -0.12, trust: -0.05, controversy: 0.1 },
      mediaVulnerabilityShift: 0.12,
      legalExposureShift: 0.18,
      scandalRiskShift: 0.22,
      coalitionRelationShift: -0.14,
      counterMobilizationRiskShift: 0.12,
    },
    risks: risk(0.7, 0.85, 0.75, 0.82, 0.55, 0.3, 0.65),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Ilegalni abstrakce s masivnim rizikem', riskLabel: 'Extremni pravni a skandalni riziko' },
  },
  {
    id: 'unverifiedLeakAbstract',
    name: 'Abstraktni neovereny unik',
    description: 'Ilegalni nebo pravne toxicka abstrakce bez operacnich detailu; ve hre primarne vytvari expozici a backlash.',
    category: 'blackOps',
    legality: 'illegal',
    ethicalRisk: 0.9,
    cost: 0.35,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.03,
    cooldownWeeks: 5,
    target: { scope: 'opponent', optional: ['party'] },
    effects: {
      fieldAmplitude: 0.005,
      reputationShift: { integrity: -0.1, trust: -0.045, controversy: 0.085 },
      mediaVulnerabilityShift: 0.13,
      legalExposureShift: 0.16,
      scandalRiskShift: 0.2,
      coalitionRelationShift: -0.12,
      counterMobilizationRiskShift: 0.1,
    },
    risks: risk(0.65, 0.8, 0.78, 0.78, 0.5, 0.24, 0.58),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Neovereny tlak s extremni expozici', riskLabel: 'Extremni riziko' },
  },
  {
    id: 'anonymousAmplificationAbstract',
    name: 'Abstraktni anonymni zesileni',
    description: 'Ilegalni black-ops abstrakce modelovana pres riziko odhaleni, ztratu integrity a koalicni toxicitu.',
    category: 'blackOps',
    legality: 'illegal',
    ethicalRisk: 0.88,
    cost: 0.3,
    staffCost: 1,
    leaderTimeCost: 0,
    fatigueCost: 0.03,
    cooldownWeeks: 5,
    target: { scope: 'national' },
    effects: {
      fieldAmplitude: 0.008,
      reputationShift: { integrity: -0.095, trust: -0.04, controversy: 0.08 },
      mediaVulnerabilityShift: 0.12,
      legalExposureShift: 0.17,
      scandalRiskShift: 0.21,
      coalitionRelationShift: -0.1,
      counterMobilizationRiskShift: 0.12,
    },
    risks: risk(0.62, 0.82, 0.74, 0.8, 0.52, 0.22, 0.56),
    preview: { visibleToPlayer: true, precisionRequired: 'seniorAdvisor', shortEffectLabel: 'Nedominantni ilegalni rizikova abstrakce', riskLabel: 'Extremni riziko' },
  },
];

export const legacyCampaignActionV2ById: Record<CampaignActionId, string> = {
  debate: 'tvDebate',
  financeTransparency: 'transparentAudit',
  focusGroup: 'focusGroup',
  internalPoll: 'internalTrackingPoll',
  leaderVisit: 'republicTour',
  messageTest: 'messageTesting',
  negativeCampaign: 'hardNegativeCampaign',
  onlineCampaign: 'billboardCampaign',
  opaqueSupport: 'anonymousAmplificationAbstract',
  parliamentSpeech: 'parliamentSpeech',
  policyPackage: 'policyPackage',
  regionalRally: 'regionalMeeting',
  schoolVisit: 'schoolVisit',
  thirdPartySupport: 'allyEcosystemAmplification',
  tvInterview: 'controlledInterview',
};

export function campaignActionV2ById(actionId: string) {
  return campaignActionsV2.find((action) => action.id === actionId);
}
