import { mediaOutlets } from "../data/mediaOutlets";
import { regions as displayRegions } from "../data/regions";
import type { RegionId } from "../types/region";

import { campaignActionsV2 } from "./campaignActionsV2";
import { nationalPartyVoteTargets2025 } from "./calibration/regionalVoteTargets2025";
import { createIssueLayerState } from "./issueSeed";
import { generateWeeklyMediaInvitations } from "./mediaEngine";
import type {
  BaselineMode,
  CoalitionRelation,
  EventCard,
  GameRules,
  GameState,
  LatentVector8D,
  LeaderTraits,
  MarketingAdvisor,
  MediaInvitation,
  MediaOutlet,
  PartyField,
  PartyId,
  PartyRuntime,
  PartySeed,
  Pollster,
  QuestionSet,
  RegionSeed,
  SegmentId,
  SponsorOffer,
  Vec3,
  VoterSegment,
} from "./types";
import { essRegionMixes, essVoterSegments } from "./voterSpace.generated";

export const partyIds: PartyId[] = [
  "player",
  "ods",
  "stan",
  "pirates",
  "kdu",
  "spd",
  "motorists",
  "top09",
  "stacilo",
  "prisaha",
  "generace",
  "others",
];

// Raw 2025 vote shares, including below-threshold and micro-party votes.
// SPOLU is split internally by its 2025 mandate ratio: ODS 27, KDU 16, TOP09 9.
export const baselineTargetShares: Record<PartyId, number> = nationalPartyVoteTargets2025;

export const DEFAULT_BASELINE_MODE: BaselineMode = "legacy-fit-national";

const vec = (econ: number, culture: number, authority: number): Vec3 => ({
  authority,
  culture,
  econ,
});

const latent8 = (
  econ: number,
  culture: number,
  authority: number,
  establishment: number,
  globalism: number,
  green: number,
  ukraine: number,
): LatentVector8D => ({
  authority,
  culture,
  econ,
  establishment,
  globalism,
  green,
  ukraine,
});

const mediaHabits = (digital = 0.4, tv = 0.4, regional = 0.2) => ({
  ct24: tv,
  metro: digital,
  region: regional,
});

export const legacyVoterSegments: VoterSegment[] = [
  {
    axisSalience: vec(0.7, 1, 0.5),
    education: "tertiary",
    id: "urbanProgressives",
    issuePrefs: {
      climate: -0.8,
      education: -0.45,
      housing: -0.5,
      transport: -0.6,
    },
    issueSalience: {
      climate: 0.9,
      education: 0.55,
      housing: 0.8,
      transport: 0.6,
    },
    mediaHabits: mediaHabits(0.78, 0.34, 0.1),
    name: "Městští progresivní voliči",
    position: vec(-0.25, -0.85, -0.65),
    scandalSensitivity: 0.9,
    turnoutBase: 0.68,
    volatility: 0.45,
  },
  {
    axisSalience: vec(1, 0.55, 0.45),
    education: "tertiary",
    id: "liberalBusiness",
    issuePrefs: { industry: 0.6, taxes: 0.82, transport: 0.3, housing: 0.2 },
    issueSalience: { industry: 0.8, taxes: 0.9, transport: 0.6, housing: 0.5 },
    mediaHabits: mediaHabits(0.65, 0.48, 0.18),
    name: "Pravicově liberální podnikatelé",
    position: vec(0.78, -0.35, -0.45),
    scandalSensitivity: 0.65,
    turnoutBase: 0.72,
    volatility: 0.35,
  },
  {
    axisSalience: vec(0.65, 0.9, 0.75),
    education: "secondary",
    id: "conservativeMiddle",
    issuePrefs: {
      security: 0.65,
      healthcare: 0.25,
      transport: 0.3,
      education: 0.25,
    },
    issueSalience: {
      security: 0.8,
      healthcare: 0.6,
      transport: 0.55,
      education: 0.45,
    },
    mediaHabits: mediaHabits(0.38, 0.65, 0.32),
    name: "Konzervativní střední třída",
    position: vec(0.25, 0.7, 0.35),
    scandalSensitivity: 0.7,
    turnoutBase: 0.69,
    volatility: 0.38,
  },
  {
    axisSalience: vec(0.85, 0.45, 0.75),
    education: "secondary",
    id: "industrialWorkers",
    issuePrefs: {
      healthcare: -0.45,
      industry: -0.2,
      security: 0.45,
      taxes: -0.2,
    },
    issueSalience: {
      healthcare: 0.7,
      industry: 0.9,
      security: 0.55,
      taxes: 0.45,
    },
    mediaHabits: mediaHabits(0.3, 0.58, 0.48),
    name: "Průmysloví zaměstnanci",
    position: vec(-0.72, 0.28, 0.45),
    scandalSensitivity: 0.45,
    turnoutBase: 0.6,
    volatility: 0.62,
  },
  {
    axisSalience: vec(0.9, 0.65, 0.55),
    education: "secondary",
    id: "seniorSocial",
    issuePrefs: { healthcare: -0.8, security: 0.35, transport: -0.2 },
    issueSalience: { healthcare: 0.95, security: 0.55, transport: 0.4 },
    mediaHabits: mediaHabits(0.2, 0.82, 0.34),
    name: "Starší sociálně citliví voliči",
    position: vec(-0.68, 0.42, 0.18),
    scandalSensitivity: 0.68,
    turnoutBase: 0.76,
    volatility: 0.28,
  },
  {
    axisSalience: vec(0.45, 0.7, 1),
    education: "lower",
    id: "protestVoters",
    issuePrefs: { security: 0.7, industry: -0.35, housing: -0.4, taxes: -0.35 },
    issueSalience: { security: 0.75, industry: 0.6, housing: 0.5, taxes: 0.45 },
    mediaHabits: mediaHabits(0.48, 0.42, 0.36),
    name: "Protestní anti-establishment voliči",
    position: vec(-0.2, 0.25, 0.9),
    scandalSensitivity: 0.25,
    turnoutBase: 0.52,
    volatility: 0.8,
  },
  {
    axisSalience: vec(0.75, 0.85, 0.55),
    education: "tertiary",
    id: "youngRenters",
    issuePrefs: {
      housing: -0.9,
      climate: -0.45,
      education: -0.5,
      transport: -0.45,
    },
    issueSalience: {
      housing: 1,
      climate: 0.62,
      education: 0.6,
      transport: 0.55,
    },
    mediaHabits: mediaHabits(0.86, 0.18, 0.12),
    name: "Mladí nájemníci",
    position: vec(-0.52, -0.58, -0.35),
    scandalSensitivity: 0.72,
    turnoutBase: 0.54,
    volatility: 0.7,
  },
  {
    axisSalience: vec(0.55, 0.95, 0.62),
    education: "secondary",
    id: "ruralConservatives",
    issuePrefs: {
      security: 0.65,
      transport: -0.25,
      healthcare: -0.35,
      climate: 0.25,
    },
    issueSalience: {
      security: 0.72,
      transport: 0.62,
      healthcare: 0.7,
      climate: 0.35,
    },
    mediaHabits: mediaHabits(0.24, 0.62, 0.66),
    name: "Venkovští konzervativci",
    position: vec(-0.05, 0.82, 0.5),
    scandalSensitivity: 0.58,
    turnoutBase: 0.7,
    volatility: 0.42,
  },
  {
    axisSalience: vec(0.85, 0.42, 0.42),
    education: "tertiary",
    id: "publicSector",
    issuePrefs: {
      healthcare: -0.72,
      education: -0.78,
      housing: -0.35,
      taxes: -0.45,
    },
    issueSalience: {
      healthcare: 0.82,
      education: 0.9,
      housing: 0.52,
      taxes: 0.5,
    },
    mediaHabits: mediaHabits(0.52, 0.62, 0.25),
    name: "Veřejný sektor a služby",
    position: vec(-0.62, -0.18, -0.2),
    scandalSensitivity: 0.75,
    turnoutBase: 0.66,
    volatility: 0.44,
  },
  {
    axisSalience: vec(0.42, 0.78, 1),
    education: "secondary",
    id: "securityHawks",
    issuePrefs: { security: 0.92, industry: 0.28, taxes: 0.2 },
    issueSalience: { security: 1, industry: 0.45, taxes: 0.35 },
    mediaHabits: mediaHabits(0.36, 0.7, 0.3),
    name: "Bezpečnostně orientovaní voliči",
    position: vec(0.2, 0.58, 0.82),
    scandalSensitivity: 0.5,
    turnoutBase: 0.67,
    volatility: 0.46,
  },
  {
    axisSalience: vec(0.65, 0.58, 0.58),
    education: "secondary",
    id: "regionalPragmatists",
    issuePrefs: {
      transport: -0.65,
      healthcare: -0.45,
      industry: 0.1,
      education: -0.25,
    },
    issueSalience: {
      transport: 0.9,
      healthcare: 0.72,
      industry: 0.55,
      education: 0.4,
    },
    mediaHabits: mediaHabits(0.34, 0.44, 0.78),
    name: "Regionální pragmatici",
    position: vec(-0.18, 0.25, 0.15),
    scandalSensitivity: 0.55,
    turnoutBase: 0.64,
    volatility: 0.5,
  },
  {
    axisSalience: vec(0.55, 0.55, 0.45),
    education: "secondary",
    id: "undecidedCenter",
    issuePrefs: {
      housing: -0.2,
      healthcare: -0.25,
      security: 0.22,
      transport: 0.05,
    },
    issueSalience: {
      housing: 0.52,
      healthcare: 0.58,
      security: 0.52,
      transport: 0.46,
    },
    mediaHabits: mediaHabits(0.48, 0.48, 0.35),
    name: "Nerozhodnutý střed",
    position: vec(0.02, 0.05, 0.02),
    scandalSensitivity: 0.62,
    turnoutBase: 0.57,
    volatility: 0.74,
  },
];

export const voterSegments: VoterSegment[] = essVoterSegments;

const mix = (values: Partial<Record<SegmentId, number>>) => values;

export const legacyRegionMixes: Record<
  RegionId,
  Partial<Record<SegmentId, number>>
> = {
  jihocesky: mix({
    ruralConservatives: 0.16,
    regionalPragmatists: 0.16,
    seniorSocial: 0.13,
    conservativeMiddle: 0.12,
    industrialWorkers: 0.1,
    publicSector: 0.1,
    undecidedCenter: 0.09,
    liberalBusiness: 0.06,
    protestVoters: 0.05,
    urbanProgressives: 0.03,
  }),
  jihomoravsky: mix({
    urbanProgressives: 0.15,
    youngRenters: 0.12,
    liberalBusiness: 0.12,
    conservativeMiddle: 0.13,
    publicSector: 0.1,
    regionalPragmatists: 0.1,
    seniorSocial: 0.09,
    industrialWorkers: 0.08,
    undecidedCenter: 0.07,
    ruralConservatives: 0.04,
  }),
  karlovarsky: mix({
    protestVoters: 0.18,
    industrialWorkers: 0.16,
    seniorSocial: 0.15,
    regionalPragmatists: 0.12,
    ruralConservatives: 0.1,
    undecidedCenter: 0.09,
    publicSector: 0.07,
    conservativeMiddle: 0.06,
    youngRenters: 0.04,
    liberalBusiness: 0.03,
  }),
  kralovehradecky: mix({
    conservativeMiddle: 0.15,
    regionalPragmatists: 0.14,
    seniorSocial: 0.12,
    ruralConservatives: 0.12,
    publicSector: 0.11,
    liberalBusiness: 0.09,
    urbanProgressives: 0.08,
    industrialWorkers: 0.07,
    undecidedCenter: 0.07,
    securityHawks: 0.05,
  }),
  liberecky: mix({
    urbanProgressives: 0.12,
    regionalPragmatists: 0.13,
    conservativeMiddle: 0.12,
    publicSector: 0.1,
    industrialWorkers: 0.1,
    protestVoters: 0.09,
    liberalBusiness: 0.09,
    youngRenters: 0.08,
    seniorSocial: 0.08,
    undecidedCenter: 0.09,
  }),
  moravskoslezsky: mix({
    industrialWorkers: 0.21,
    protestVoters: 0.15,
    seniorSocial: 0.12,
    publicSector: 0.1,
    regionalPragmatists: 0.1,
    securityHawks: 0.09,
    conservativeMiddle: 0.08,
    undecidedCenter: 0.07,
    youngRenters: 0.05,
    urbanProgressives: 0.03,
  }),
  olomoucky: mix({
    regionalPragmatists: 0.14,
    publicSector: 0.13,
    seniorSocial: 0.12,
    ruralConservatives: 0.11,
    industrialWorkers: 0.1,
    conservativeMiddle: 0.1,
    youngRenters: 0.08,
    undecidedCenter: 0.08,
    urbanProgressives: 0.07,
    protestVoters: 0.07,
  }),
  pardubicky: mix({
    regionalPragmatists: 0.16,
    conservativeMiddle: 0.13,
    publicSector: 0.12,
    industrialWorkers: 0.11,
    seniorSocial: 0.1,
    ruralConservatives: 0.1,
    liberalBusiness: 0.08,
    undecidedCenter: 0.08,
    securityHawks: 0.06,
    protestVoters: 0.06,
  }),
  plzensky: mix({
    industrialWorkers: 0.14,
    liberalBusiness: 0.12,
    conservativeMiddle: 0.12,
    regionalPragmatists: 0.12,
    securityHawks: 0.1,
    seniorSocial: 0.1,
    publicSector: 0.09,
    protestVoters: 0.08,
    urbanProgressives: 0.07,
    undecidedCenter: 0.06,
  }),
  praha: mix({
    urbanProgressives: 0.24,
    youngRenters: 0.16,
    liberalBusiness: 0.16,
    publicSector: 0.09,
    conservativeMiddle: 0.09,
    undecidedCenter: 0.08,
    securityHawks: 0.05,
    seniorSocial: 0.05,
    protestVoters: 0.04,
    regionalPragmatists: 0.04,
  }),
  stredocesky: mix({
    conservativeMiddle: 0.15,
    liberalBusiness: 0.12,
    regionalPragmatists: 0.12,
    youngRenters: 0.1,
    publicSector: 0.1,
    seniorSocial: 0.1,
    ruralConservatives: 0.09,
    industrialWorkers: 0.08,
    undecidedCenter: 0.08,
    urbanProgressives: 0.06,
  }),
  ustecky: mix({
    industrialWorkers: 0.2,
    protestVoters: 0.18,
    seniorSocial: 0.12,
    securityHawks: 0.1,
    regionalPragmatists: 0.1,
    publicSector: 0.08,
    conservativeMiddle: 0.07,
    undecidedCenter: 0.07,
    ruralConservatives: 0.05,
    youngRenters: 0.03,
  }),
  vysocina: mix({
    ruralConservatives: 0.18,
    regionalPragmatists: 0.16,
    seniorSocial: 0.13,
    conservativeMiddle: 0.12,
    publicSector: 0.11,
    industrialWorkers: 0.08,
    securityHawks: 0.07,
    undecidedCenter: 0.06,
    protestVoters: 0.05,
    liberalBusiness: 0.04,
  }),
  zlinsky: mix({
    ruralConservatives: 0.17,
    conservativeMiddle: 0.15,
    regionalPragmatists: 0.14,
    securityHawks: 0.1,
    seniorSocial: 0.1,
    industrialWorkers: 0.09,
    publicSector: 0.08,
    liberalBusiness: 0.07,
    undecidedCenter: 0.06,
    protestVoters: 0.04,
  }),
};

const regionMixes: Record<
  RegionId,
  Partial<Record<SegmentId, number>>
> = essRegionMixes;

const agendas: Record<RegionId, RegionSeed["issueAgendaBase"]> = {
  jihocesky: {
    healthcare: 0.72,
    transport: 0.62,
    climate: 0.35,
    industry: 0.4,
  },
  jihomoravsky: {
    housing: 0.68,
    transport: 0.65,
    industry: 0.48,
    education: 0.56,
  },
  karlovarsky: {
    healthcare: 0.8,
    industry: 0.58,
    housing: 0.52,
    transport: 0.44,
  },
  kralovehradecky: {
    healthcare: 0.68,
    transport: 0.62,
    education: 0.45,
    security: 0.5,
  },
  liberecky: { transport: 0.66, climate: 0.52, housing: 0.48, industry: 0.42 },
  moravskoslezsky: {
    industry: 0.92,
    healthcare: 0.68,
    security: 0.62,
    housing: 0.44,
  },
  olomoucky: {
    healthcare: 0.66,
    transport: 0.55,
    industry: 0.58,
    education: 0.45,
  },
  pardubicky: {
    transport: 0.78,
    industry: 0.55,
    housing: 0.42,
    education: 0.44,
  },
  plzensky: { industry: 0.76, transport: 0.58, security: 0.55, taxes: 0.4 },
  praha: { climate: 0.72, education: 0.62, housing: 0.95, transport: 0.78 },
  stredocesky: {
    housing: 0.58,
    transport: 0.92,
    healthcare: 0.48,
    education: 0.45,
  },
  ustecky: { industry: 0.9, security: 0.72, housing: 0.5, healthcare: 0.54 },
  vysocina: { healthcare: 0.72, transport: 0.66, industry: 0.44, climate: 0.3 },
  zlinsky: { industry: 0.62, healthcare: 0.66, transport: 0.58, taxes: 0.42 },
};

const populationWeights: Record<RegionId, number> = {
  jihocesky: 0.62,
  jihomoravsky: 1.12,
  karlovarsky: 0.28,
  kralovehradecky: 0.52,
  liberecky: 0.42,
  moravskoslezsky: 1.14,
  olomoucky: 0.6,
  pardubicky: 0.49,
  plzensky: 0.56,
  praha: 1.18,
  stredocesky: 1.3,
  ustecky: 0.78,
  vysocina: 0.48,
  zlinsky: 0.55,
};

const urbanity: Record<RegionId, number> = {
  jihocesky: 0.44,
  jihomoravsky: 0.76,
  karlovarsky: 0.46,
  kralovehradecky: 0.48,
  liberecky: 0.56,
  moravskoslezsky: 0.62,
  olomoucky: 0.5,
  pardubicky: 0.46,
  plzensky: 0.55,
  praha: 1,
  stredocesky: 0.62,
  ustecky: 0.5,
  vysocina: 0.34,
  zlinsky: 0.42,
};

const turnoutModifier: Record<RegionId, number> = {
  jihocesky: 0,
  jihomoravsky: 0.04,
  karlovarsky: -0.09,
  kralovehradecky: 0.02,
  liberecky: -0.01,
  moravskoslezsky: -0.06,
  olomoucky: -0.02,
  pardubicky: 0,
  plzensky: -0.01,
  praha: 0.06,
  stredocesky: 0.02,
  ustecky: -0.08,
  vysocina: 0.03,
  zlinsky: 0.01,
};

export const regionSeeds: RegionSeed[] = displayRegions.map((region) => ({
  id: region.id,
  issueAgendaBase: agendas[region.id],
  name: region.name,
  populationWeight: populationWeights[region.id],
  segmentMix: regionMixes[region.id],
  turnoutModifier: turnoutModifier[region.id],
  urbanity: urbanity[region.id],
}));

const leader = (
  charisma: number,
  credibility: number,
  debate: number,
  discipline: number,
  empathy: number,
  knowledge: number,
  stamina: number,
): LeaderTraits => ({
  charisma,
  credibility,
  debate,
  discipline,
  empathy,
  knowledge,
  stamina,
});

type PartyFieldSeed = {
  amplitude: number;
  center: LatentVector8D;
  originCenter: LatentVector8D;
  width: LatentVector8D;
  salience?: LatentVector8D;
  flexibility: number;
};

type RegionOrganizationBase = Record<RegionId, number>;

// Center dimensions use -1..1. Econ: left/state-led to market-liberal.
// Culture: progressive/urban to conservative/localist. Authority: civil-libertarian to law-and-order.
// Establishment: anti-system to institutional. Globalism: sovereign/localist to open/pro-EU.
// Green: industrial/fossil-pragmatic to ecological. Ukraine: skeptical to pro-Ukraine/Atlantic.
// Amplitude is baseline visibility; width is voter-tent breadth; salience is how much mismatch hurts;
// flexibility is how easily the party can move from its origin without coherence costs.
const partyField = (seed: PartyFieldSeed): PartyField => ({
  amplitude: seed.amplitude,
  center: vec(seed.center.econ, seed.center.culture, seed.center.authority),
  center8D: { ...seed.center },
  flexibility: seed.flexibility,
  originCenter: vec(
    seed.originCenter.econ,
    seed.originCenter.culture,
    seed.originCenter.authority,
  ),
  originCenter8D: { ...seed.originCenter },
  salience8D: { ...(seed.salience ?? defaultSalience8D()) },
  width: vec(seed.width.econ, seed.width.culture, seed.width.authority),
  width8D: { ...seed.width },
});

const organization = (values: RegionOrganizationBase) => values;

function defaultSalience8D(): LatentVector8D {
  return latent8(1, 1, 1, 0.85, 0.9, 0.85, 0.9);
}

function zeroPartyRecord<T>(value: T): Record<PartyId, T> {
  return Object.fromEntries(
    partyIds.map((partyId) => [partyId, value]),
  ) as Record<PartyId, T>;
}

function zeroPollRecord(): GameState["polls"] {
  return Object.fromEntries(
    partyIds.map((partyId) => [partyId, { high: 0, low: 0, value: 0 }]),
  ) as GameState["polls"];
}

export const parties: PartySeed[] = [
  // player / ANO 2011: dominant populist catch-all, welfare-and-managerial appeal, moderately conservative, anti-Green-Deal leaning.
  {
    coalitionBase: {
      ods: 0.22,
      stan: 0.18,
      pirates: 0.12,
      kdu: 0.24,
      spd: 0.5,
      motorists: 0.58,
      top09: 0.16,
      stacilo: 0.56,
      prisaha: 0.45,
      generace: 0.22,
      others: 0.08,
    },
    color: "#261E82",
    field: partyField({
      amplitude: 1,
      center: latent8(-0.22, 0.28, 0.45, -0.28, -0.18, -0.28, -0.08),
      flexibility: 0.72,
      originCenter: latent8(-0.22, 0.28, 0.45, -0.28, -0.18, -0.28, -0.08),
      width: latent8(0.7, 0.64, 0.62, 0.64, 0.64, 0.64, 0.64),
      salience: latent8(1.15, 0.8, 1.05, 0.9, 0.75, 0.8, 0.7),
    }),
    baselineTargetShare: baselineTargetShares.player,
    id: "player",
    issueOwnership: {
      healthcare: 0.72,
      housing: 0.48,
      industry: 0.52,
      security: 0.58,
      taxes: 0.5,
      transport: 0.42,
    },
    issuePositions: {
      climate: 0.35,
      education: 0.05,
      healthcare: -0.55,
      housing: -0.35,
      industry: 0.15,
      security: 0.5,
      taxes: 0.15,
      transport: -0.1,
    },
    leaderName: "Andrej Babiš",
    leaderTraits: leader(0.72, 0.48, 0.7, 0.48, 0.52, 0.58, 0.68),
    name: "ANO 2011",
    officeRole: "government",
    organizationBase: organization({
      praha: 0.5,
      stredocesky: 0.72,
      jihocesky: 0.74,
      plzensky: 0.76,
      karlovarsky: 0.86,
      ustecky: 0.88,
      liberecky: 0.74,
      kralovehradecky: 0.72,
      pardubicky: 0.73,
      vysocina: 0.7,
      jihomoravsky: 0.68,
      olomoucky: 0.72,
      zlinsky: 0.7,
      moravskoslezsky: 0.84,
    }),
    playable: true,
    reputation: {
      authenticity: 0.6,
      competence: 0.62,
      consistency: 0.52,
      controversy: 0.48,
      integrity: 0.38,
      trust: 0.55,
    },
    shortName: "ANO",
    startingCash: 18,
    weeklyStaffCap: 7,
    winProfile: "major",
  },

  // ODS: mainstream centre-right conservative party, pro-West, fiscally right, anti-Green-Deal leaning but institutionally pro-system.
  {
    coalitionBase: {
      player: 0.22,
      stan: 0.7,
      pirates: 0.45,
      kdu: 0.72,
      spd: 0.18,
      motorists: 0.62,
      top09: 0.78,
      stacilo: 0.08,
      prisaha: 0.22,
      generace: 0.28,
      others: 0.06,
    },
    color: "#034EA2",
    field: partyField({
      amplitude: 0.92,
      center: latent8(0.62, 0.38, 0.32, 0.28, 0.28, -0.35, 0.52),
      flexibility: 0.48,
      originCenter: latent8(0.62, 0.38, 0.32, 0.28, 0.28, -0.35, 0.52),
      width: latent8(0.62, 0.58, 0.6, 0.66, 0.62, 0.58, 0.58),
      salience: latent8(1.25, 0.95, 0.9, 1.0, 0.85, 0.95, 1.0),
    }),
    baselineTargetShare: baselineTargetShares.ods,
    id: "ods",
    issueOwnership: {
      education: 0.42,
      industry: 0.58,
      security: 0.62,
      taxes: 0.76,
      transport: 0.48,
    },
    issuePositions: {
      climate: 0.45,
      education: 0.1,
      healthcare: 0.05,
      housing: 0.25,
      industry: 0.55,
      security: 0.55,
      taxes: 0.78,
      transport: 0.35,
    },
    leaderName: "Martin Kupka",
    leaderTraits: leader(0.56, 0.66, 0.58, 0.68, 0.44, 0.68, 0.56),
    name: "Občanská demokratická strana",
    officeRole: "opposition",
    organizationBase: organization({
      praha: 0.62,
      stredocesky: 0.54,
      jihocesky: 0.5,
      plzensky: 0.5,
      karlovarsky: 0.34,
      ustecky: 0.33,
      liberecky: 0.38,
      kralovehradecky: 0.5,
      pardubicky: 0.52,
      vysocina: 0.42,
      jihomoravsky: 0.58,
      olomoucky: 0.4,
      zlinsky: 0.42,
      moravskoslezsky: 0.38,
    }),
    playable: false,
    reputation: {
      authenticity: 0.44,
      competence: 0.6,
      consistency: 0.62,
      controversy: 0.34,
      integrity: 0.54,
      trust: 0.5,
    },
    shortName: "ODS",
    startingCash: 8,
    weeklyStaffCap: 5.5,
    winProfile: "mid",
  },

  // STAN: liberal pro-European regional/municipal party, institutional, decentralizing, strongest in suburban and local-governance segments.
  {
    coalitionBase: {
      player: 0.18,
      ods: 0.7,
      pirates: 0.72,
      kdu: 0.58,
      spd: 0.1,
      motorists: 0.28,
      top09: 0.72,
      stacilo: 0.06,
      prisaha: 0.18,
      generace: 0.3,
      others: 0.06,
    },
    color: "#7CB342",
    field: partyField({
      amplitude: 0.83,
      center: latent8(0.18, -0.12, -0.02, 0.38, 0.65, 0.28, 0.62),
      flexibility: 0.62,
      originCenter: latent8(0.18, -0.12, -0.02, 0.38, 0.65, 0.28, 0.62),
      width: latent8(0.52, 0.54, 0.52, 0.66, 0.61, 0.52, 0.58),
      salience: latent8(0.8, 0.75, 0.65, 1.35, 1.35, 0.8, 1.1),
    }),
    baselineTargetShare: baselineTargetShares.stan,
    id: "stan",
    issueOwnership: {
      education: 0.52,
      healthcare: 0.38,
      housing: 0.42,
      transport: 0.72,
    },
    issuePositions: {
      climate: -0.25,
      education: -0.35,
      healthcare: -0.2,
      housing: -0.15,
      industry: 0.05,
      security: 0.18,
      taxes: 0.2,
      transport: -0.45,
    },
    leaderName: "Vít Rakušan",
    leaderTraits: leader(0.68, 0.56, 0.62, 0.54, 0.58, 0.6, 0.62),
    name: "Starostové a nezávislí",
    officeRole: "opposition",
    organizationBase: organization({
      praha: 0.48,
      stredocesky: 0.62,
      jihocesky: 0.44,
      plzensky: 0.45,
      karlovarsky: 0.48,
      ustecky: 0.42,
      liberecky: 0.72,
      kralovehradecky: 0.55,
      pardubicky: 0.5,
      vysocina: 0.45,
      jihomoravsky: 0.58,
      olomoucky: 0.48,
      zlinsky: 0.42,
      moravskoslezsky: 0.42,
    }),
    playable: false,
    reputation: {
      authenticity: 0.58,
      competence: 0.56,
      consistency: 0.5,
      controversy: 0.32,
      integrity: 0.5,
      trust: 0.5,
    },
    shortName: "STAN",
    startingCash: 7,
    weeklyStaffCap: 5,
    winProfile: "mid",
  },

  // Pirates: progressive liberal digital/transparency party, strong in Prague and younger urban electorate, pro-EU and pro-Ukraine.
  {
    coalitionBase: {
      player: 0.12,
      ods: 0.45,
      stan: 0.72,
      kdu: 0.38,
      spd: 0.05,
      motorists: 0.12,
      top09: 0.55,
      stacilo: 0.04,
      prisaha: 0.12,
      generace: 0.26,
      others: 0.05,
    },
    color: "#111111",
    field: partyField({
      amplitude: 0.78,
      center: latent8(-0.18, -0.62, -0.42, 0.08, 0.68, 0.5, 0.65),
      flexibility: 0.58,
      originCenter: latent8(-0.18, -0.62, -0.42, 0.08, 0.68, 0.5, 0.65),
      width: latent8(0.58, 0.52, 0.56, 0.62, 0.58, 0.6, 0.56),
      salience: latent8(0.8, 1.15, 1.0, 1.0, 1.15, 1.05, 1.05),
    }),
    baselineTargetShare: baselineTargetShares.pirates,
    id: "pirates",
    issueOwnership: {
      climate: 0.52,
      education: 0.58,
      housing: 0.68,
      transport: 0.35,
    },
    issuePositions: {
      climate: -0.65,
      education: -0.55,
      healthcare: -0.25,
      housing: -0.65,
      industry: -0.2,
      security: -0.3,
      taxes: -0.1,
      transport: -0.35,
    },
    leaderName: "Zdeněk Hřib",
    leaderTraits: leader(0.58, 0.54, 0.56, 0.52, 0.5, 0.62, 0.56),
    name: "Česká pirátská strana",
    officeRole: "opposition",
    organizationBase: organization({
      praha: 0.78,
      stredocesky: 0.48,
      jihocesky: 0.4,
      plzensky: 0.42,
      karlovarsky: 0.32,
      ustecky: 0.36,
      liberecky: 0.42,
      kralovehradecky: 0.4,
      pardubicky: 0.38,
      vysocina: 0.32,
      jihomoravsky: 0.5,
      olomoucky: 0.42,
      zlinsky: 0.34,
      moravskoslezsky: 0.42,
    }),
    playable: false,
    reputation: {
      authenticity: 0.64,
      competence: 0.5,
      consistency: 0.58,
      controversy: 0.3,
      integrity: 0.62,
      trust: 0.48,
    },
    shortName: "Piráti",
    startingCash: 5.8,
    weeklyStaffCap: 4.5,
    winProfile: "mid",
  },

  // KDU-ČSL: Christian-democratic social-market party, conservative on culture, stronger in Moravia and rural/local networks.
  {
    coalitionBase: {
      player: 0.24,
      ods: 0.72,
      stan: 0.58,
      pirates: 0.38,
      spd: 0.18,
      motorists: 0.42,
      top09: 0.68,
      stacilo: 0.08,
      prisaha: 0.2,
      generace: 0.25,
      others: 0.06,
    },
    color: "#F6C500",
    field: partyField({
      amplitude: 0.68,
      center: latent8(-0.05, 0.68, 0.22, 0.22, 0.28, 0.08, 0.42),
      flexibility: 0.44,
      originCenter: latent8(-0.05, 0.68, 0.22, 0.22, 0.28, 0.08, 0.42),
      width: latent8(0.54, 0.42, 0.52, 0.64, 0.54, 0.5, 0.58),
      salience: latent8(0.75, 1.25, 0.8, 0.95, 0.85, 0.65, 0.85),
    }),
    baselineTargetShare: baselineTargetShares.kdu,
    id: "kdu",
    issueOwnership: {
      education: 0.56,
      healthcare: 0.62,
      housing: 0.42,
      transport: 0.35,
    },
    issuePositions: {
      climate: -0.05,
      education: 0.05,
      healthcare: -0.4,
      housing: -0.25,
      industry: 0.15,
      security: 0.25,
      taxes: 0.05,
      transport: -0.15,
    },
    leaderName: "Jan Grolich",
    leaderTraits: leader(0.62, 0.56, 0.52, 0.58, 0.66, 0.54, 0.6),
    name: "KDU-ČSL",
    officeRole: "opposition",
    organizationBase: organization({
      praha: 0.32,
      stredocesky: 0.42,
      jihocesky: 0.45,
      plzensky: 0.34,
      karlovarsky: 0.28,
      ustecky: 0.28,
      liberecky: 0.32,
      kralovehradecky: 0.42,
      pardubicky: 0.46,
      vysocina: 0.58,
      jihomoravsky: 0.72,
      olomoucky: 0.58,
      zlinsky: 0.66,
      moravskoslezsky: 0.46,
    }),
    playable: false,
    reputation: {
      authenticity: 0.56,
      competence: 0.5,
      consistency: 0.62,
      controversy: 0.26,
      integrity: 0.58,
      trust: 0.48,
    },
    shortName: "KDU",
    startingCash: 4.8,
    weeklyStaffCap: 4,
    winProfile: "small",
  },

  // SPD: nationalist anti-immigration, anti-EU/anti-NATO protest party; high salience on sovereignty, authority and Ukraine/globalism axes.
  {
    coalitionBase: {
      player: 0.5,
      ods: 0.18,
      stan: 0.1,
      pirates: 0.05,
      kdu: 0.18,
      motorists: 0.62,
      top09: 0.08,
      stacilo: 0.42,
      prisaha: 0.46,
      generace: 0.2,
      others: 0.08,
    },
    color: "#004B8D",
    field: partyField({
      amplitude: 0.72,
      center: latent8(-0.12, 0.74, 0.7, -0.68, -0.7, -0.62, -0.65),
      flexibility: 0.36,
      originCenter: latent8(-0.12, 0.74, 0.7, -0.68, -0.7, -0.62, -0.65),
      width: latent8(0.64, 0.56, 0.56, 0.62, 0.6, 0.54, 0.6),
      salience: latent8(0.8, 1.35, 1.3, 1.25, 1.45, 0.9, 1.35),
    }),
    baselineTargetShare: baselineTargetShares.spd,
    id: "spd",
    issueOwnership: {
      industry: 0.48,
      security: 0.88,
      taxes: 0.36,
      transport: 0.3,
    },
    issuePositions: {
      climate: 0.65,
      education: 0.35,
      healthcare: -0.25,
      housing: -0.2,
      industry: 0.45,
      security: 0.9,
      taxes: -0.15,
      transport: 0.0,
    },
    leaderName: "Tomio Okamura",
    leaderTraits: leader(0.7, 0.42, 0.74, 0.5, 0.34, 0.46, 0.62),
    name: "Svoboda a přímá demokracie",
    officeRole: "government",
    organizationBase: organization({
      praha: 0.36,
      stredocesky: 0.5,
      jihocesky: 0.52,
      plzensky: 0.56,
      karlovarsky: 0.68,
      ustecky: 0.64,
      liberecky: 0.56,
      kralovehradecky: 0.5,
      pardubicky: 0.5,
      vysocina: 0.52,
      jihomoravsky: 0.46,
      olomoucky: 0.5,
      zlinsky: 0.52,
      moravskoslezsky: 0.58,
    }),
    playable: false,
    reputation: {
      authenticity: 0.66,
      competence: 0.38,
      consistency: 0.68,
      controversy: 0.68,
      integrity: 0.42,
      trust: 0.42,
    },
    shortName: "SPD",
    startingCash: 6.2,
    weeklyStaffCap: 4.5,
    winProfile: "small",
  },

  // Motorists: right-wing anti-Green-Deal/libertarian-conservative party; strongest distinction is green/globalism/econ profile.
  {
    coalitionBase: {
      player: 0.58,
      ods: 0.62,
      stan: 0.28,
      pirates: 0.12,
      kdu: 0.42,
      spd: 0.62,
      top09: 0.48,
      stacilo: 0.26,
      prisaha: 0.48,
      generace: 0.24,
      others: 0.07,
    },
    color: "#1E1E1E",
    field: partyField({
      amplitude: 0.67,
      center: latent8(0.66, 0.5, 0.48, -0.38, -0.42, -0.68, -0.28),
      flexibility: 0.58,
      originCenter: latent8(0.66, 0.5, 0.48, -0.38, -0.42, -0.68, -0.28),
      width: latent8(0.64, 0.58, 0.58, 0.64, 0.62, 0.64, 0.56),
      salience: latent8(1.25, 0.85, 0.85, 0.85, 1.05, 1.25, 0.8),
    }),
    baselineTargetShare: baselineTargetShares.motorists,
    id: "motorists",
    issueOwnership: {
      climate: 0.74,
      industry: 0.58,
      taxes: 0.62,
      transport: 0.82,
    },
    issuePositions: {
      climate: 0.95,
      education: 0.15,
      healthcare: 0.1,
      housing: 0.25,
      industry: 0.72,
      security: 0.45,
      taxes: 0.85,
      transport: 0.72,
    },
    leaderName: "Petr Macinka",
    leaderTraits: leader(0.62, 0.46, 0.6, 0.48, 0.34, 0.48, 0.58),
    name: "Motoristé sobě",
    officeRole: "government",
    organizationBase: organization({
      praha: 0.45,
      stredocesky: 0.58,
      jihocesky: 0.52,
      plzensky: 0.54,
      karlovarsky: 0.5,
      ustecky: 0.5,
      liberecky: 0.52,
      kralovehradecky: 0.56,
      pardubicky: 0.58,
      vysocina: 0.48,
      jihomoravsky: 0.52,
      olomoucky: 0.48,
      zlinsky: 0.5,
      moravskoslezsky: 0.48,
    }),
    playable: false,
    reputation: {
      authenticity: 0.58,
      competence: 0.42,
      consistency: 0.52,
      controversy: 0.52,
      integrity: 0.44,
      trust: 0.4,
    },
    shortName: "AUTO",
    startingCash: 5.5,
    weeklyStaffCap: 4,
    winProfile: "small",
  },

  // TOP 09: liberal-conservative, strongly pro-EU/pro-Ukraine, fiscally right, Prague-heavy and elite/urban profile.
  {
    coalitionBase: {
      player: 0.16,
      ods: 0.78,
      stan: 0.72,
      pirates: 0.55,
      kdu: 0.68,
      spd: 0.08,
      motorists: 0.48,
      stacilo: 0.04,
      prisaha: 0.14,
      generace: 0.28,
      others: 0.05,
    },
    color: "#7B1FA2",
    field: partyField({
      amplitude: 0.58,
      center: latent8(0.72, -0.08, 0.02, 0.48, 0.72, 0.32, 0.78),
      flexibility: 0.42,
      originCenter: latent8(0.72, -0.08, 0.02, 0.48, 0.72, 0.32, 0.78),
      width: latent8(0.54, 0.56, 0.58, 0.56, 0.56, 0.52, 0.54),
      salience: latent8(1.2, 0.8, 0.65, 1.15, 1.15, 0.75, 1.15),
    }),
    baselineTargetShare: baselineTargetShares.top09,
    id: "top09",
    issueOwnership: {
      climate: 0.35,
      education: 0.48,
      security: 0.42,
      taxes: 0.58,
    },
    issuePositions: {
      climate: -0.3,
      education: -0.2,
      healthcare: 0.05,
      housing: 0.2,
      industry: 0.35,
      security: 0.25,
      taxes: 0.85,
      transport: 0.1,
    },
    leaderName: "Matěj Ondřej Havel",
    leaderTraits: leader(0.48, 0.58, 0.52, 0.62, 0.42, 0.64, 0.5),
    name: "TOP 09",
    officeRole: "opposition",
    organizationBase: organization({
      praha: 0.68,
      stredocesky: 0.45,
      jihocesky: 0.34,
      plzensky: 0.34,
      karlovarsky: 0.26,
      ustecky: 0.32,
      liberecky: 0.34,
      kralovehradecky: 0.45,
      pardubicky: 0.36,
      vysocina: 0.32,
      jihomoravsky: 0.42,
      olomoucky: 0.32,
      zlinsky: 0.3,
      moravskoslezsky: 0.32,
    }),
    playable: false,
    reputation: {
      authenticity: 0.42,
      competence: 0.54,
      consistency: 0.58,
      controversy: 0.28,
      integrity: 0.56,
      trust: 0.42,
    },
    shortName: "TOP",
    startingCash: 4.2,
    weeklyStaffCap: 3.5,
    winProfile: "small",
  },

  // Stacilo!: left-wing anti-establishment protest list, anti-globalist and skeptical of EU/NATO/Ukraine policy.
  {
    coalitionBase: {
      player: 0.56,
      ods: 0.08,
      stan: 0.06,
      pirates: 0.04,
      kdu: 0.08,
      spd: 0.42,
      motorists: 0.26,
      top09: 0.04,
      prisaha: 0.34,
      generace: 0.16,
      others: 0.08,
    },
    color: "#B71C1C",
    field: partyField({
      amplitude: 0.42,
      center: latent8(-0.72, 0.34, 0.46, -0.78, -0.72, -0.48, -0.78),
      flexibility: 0.34,
      originCenter: latent8(-0.72, 0.34, 0.46, -0.78, -0.72, -0.48, -0.78),
      width: latent8(0.62, 0.58, 0.62, 0.58, 0.58, 0.62, 0.58),
      salience: latent8(1.2, 0.85, 0.95, 1.35, 1.25, 0.8, 1.35),
    }),
    baselineTargetShare: baselineTargetShares.stacilo,
    id: "stacilo",
    issueOwnership: {
      healthcare: 0.5,
      industry: 0.54,
      taxes: 0.36,
      security: 0.28,
    },
    issuePositions: {
      climate: 0.32,
      education: -0.2,
      healthcare: -0.65,
      housing: -0.45,
      industry: -0.15,
      security: 0.18,
      taxes: -0.4,
      transport: -0.25,
    },
    leaderName: "Katerina Konecna",
    leaderTraits: leader(0.62, 0.42, 0.64, 0.52, 0.42, 0.48, 0.58),
    mandateEligible: true,
    name: "Stacilo!",
    officeRole: "outsider",
    organizationBase: organization({
      praha: 0.24,
      stredocesky: 0.36,
      jihocesky: 0.42,
      plzensky: 0.42,
      karlovarsky: 0.5,
      ustecky: 0.58,
      liberecky: 0.42,
      kralovehradecky: 0.42,
      pardubicky: 0.44,
      vysocina: 0.48,
      jihomoravsky: 0.48,
      olomoucky: 0.56,
      zlinsky: 0.5,
      moravskoslezsky: 0.62,
    }),
    playable: false,
    reputation: {
      authenticity: 0.58,
      competence: 0.34,
      consistency: 0.62,
      controversy: 0.64,
      integrity: 0.38,
      trust: 0.34,
    },
    shortName: "STAC",
    startingCash: 2.4,
    weeklyStaffCap: 2.4,
    winProfile: "outsider",
  },

  // Prisaha: law-and-order anti-corruption protest movement, less ideological than SPD or Stacilo.
  {
    coalitionBase: {
      player: 0.45,
      ods: 0.22,
      stan: 0.18,
      pirates: 0.12,
      kdu: 0.2,
      spd: 0.46,
      motorists: 0.48,
      top09: 0.14,
      stacilo: 0.34,
      generace: 0.24,
      others: 0.08,
    },
    color: "#00695C",
    field: partyField({
      amplitude: 0.24,
      center: latent8(0.02, 0.34, 0.62, -0.52, -0.22, -0.24, -0.22),
      flexibility: 0.52,
      originCenter: latent8(0.02, 0.34, 0.62, -0.52, -0.22, -0.24, -0.22),
      width: latent8(0.66, 0.64, 0.54, 0.64, 0.62, 0.62, 0.62),
      salience: latent8(0.75, 0.8, 1.25, 1.2, 0.75, 0.6, 0.7),
    }),
    baselineTargetShare: baselineTargetShares.prisaha,
    id: "prisaha",
    issueOwnership: {
      security: 0.62,
      taxes: 0.32,
      transport: 0.24,
    },
    issuePositions: {
      climate: 0.22,
      education: 0.0,
      healthcare: -0.1,
      housing: -0.12,
      industry: 0.18,
      security: 0.72,
      taxes: 0.1,
      transport: 0.1,
    },
    leaderName: "Robert Slachta",
    leaderTraits: leader(0.52, 0.48, 0.54, 0.58, 0.38, 0.46, 0.56),
    mandateEligible: true,
    name: "Prisaha",
    officeRole: "outsider",
    organizationBase: organization({
      praha: 0.18,
      stredocesky: 0.22,
      jihocesky: 0.24,
      plzensky: 0.22,
      karlovarsky: 0.22,
      ustecky: 0.24,
      liberecky: 0.2,
      kralovehradecky: 0.22,
      pardubicky: 0.24,
      vysocina: 0.25,
      jihomoravsky: 0.3,
      olomoucky: 0.25,
      zlinsky: 0.24,
      moravskoslezsky: 0.22,
    }),
    playable: false,
    reputation: {
      authenticity: 0.5,
      competence: 0.36,
      consistency: 0.48,
      controversy: 0.44,
      integrity: 0.48,
      trust: 0.34,
    },
    shortName: "PRI",
    startingCash: 1.2,
    weeklyStaffCap: 1.6,
    winProfile: "outsider",
  },

  // Generace: very small broad centrist protest actor with weak and diffuse voter field.
  {
    coalitionBase: {
      player: 0.22,
      ods: 0.28,
      stan: 0.3,
      pirates: 0.26,
      kdu: 0.25,
      spd: 0.2,
      motorists: 0.24,
      top09: 0.28,
      stacilo: 0.16,
      prisaha: 0.24,
      others: 0.1,
    },
    color: "#607D8B",
    field: partyField({
      amplitude: 0.16,
      center: latent8(0.04, 0.12, 0.24, -0.46, -0.08, -0.04, 0.06),
      flexibility: 0.58,
      originCenter: latent8(0.04, 0.12, 0.24, -0.46, -0.08, -0.04, 0.06),
      width: latent8(0.46, 0.44, 0.42, 0.4, 0.48, 0.48, 0.46),
      salience: latent8(0.95, 1.0, 1.1, 1.15, 0.95, 0.9, 0.95),
    }),
    baselineTargetShare: baselineTargetShares.generace,
    id: "generace",
    issueOwnership: {
      education: 0.22,
      housing: 0.18,
      transport: 0.16,
    },
    issuePositions: {
      climate: -0.05,
      education: -0.15,
      healthcare: -0.05,
      housing: -0.1,
      industry: 0.0,
      security: 0.08,
      taxes: 0.05,
      transport: -0.05,
    },
    leaderName: "Hnuti Generace",
    leaderTraits: leader(0.36, 0.3, 0.32, 0.36, 0.42, 0.34, 0.38),
    mandateEligible: true,
    name: "Hnuti Generace",
    officeRole: "outsider",
    organizationBase: organization({
      praha: 0.12,
      stredocesky: 0.12,
      jihocesky: 0.1,
      plzensky: 0.1,
      karlovarsky: 0.08,
      ustecky: 0.08,
      liberecky: 0.1,
      kralovehradecky: 0.1,
      pardubicky: 0.1,
      vysocina: 0.1,
      jihomoravsky: 0.11,
      olomoucky: 0.09,
      zlinsky: 0.09,
      moravskoslezsky: 0.08,
    }),
    playable: false,
    reputation: {
      authenticity: 0.34,
      competence: 0.22,
      consistency: 0.28,
      controversy: 0.18,
      integrity: 0.38,
      trust: 0.2,
    },
    shortName: "GEN",
    startingCash: 0.5,
    weeklyStaffCap: 0.8,
    winProfile: "outsider",
  },

  // Others: aggregate of micro-subjects; included in vote shares but excluded from mandate allocation.
  // TODO(calibration): replace this temporary niche field with residual allocation outside spatial utility.
  {
    coalitionBase: {},
    color: "#9E9E9E",
    field: partyField({
      amplitude: 0.05,
      center: latent8(-0.08, 0.18, 0.18, -0.42, -0.18, -0.12, -0.1),
      flexibility: 0.45,
      originCenter: latent8(-0.08, 0.18, 0.18, -0.42, -0.18, -0.12, -0.1),
      width: latent8(0.44, 0.46, 0.44, 0.38, 0.46, 0.48, 0.46),
      salience: latent8(0.95, 0.95, 1.0, 1.15, 0.95, 0.9, 0.95),
    }),
    baselineTargetShare: baselineTargetShares.others,
    id: "others",
    issueOwnership: {},
    issuePositions: {},
    leaderName: "Mikrosubjekty",
    leaderTraits: leader(0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2),
    mandateEligible: false,
    name: "Ostatni",
    officeRole: "outsider",
    organizationBase: organization({
      praha: 0.08,
      stredocesky: 0.08,
      jihocesky: 0.08,
      plzensky: 0.08,
      karlovarsky: 0.08,
      ustecky: 0.08,
      liberecky: 0.08,
      kralovehradecky: 0.08,
      pardubicky: 0.08,
      vysocina: 0.08,
      jihomoravsky: 0.08,
      olomoucky: 0.08,
      zlinsky: 0.08,
      moravskoslezsky: 0.08,
    }),
    playable: false,
    reputation: {
      authenticity: 0.24,
      competence: 0.16,
      consistency: 0.18,
      controversy: 0.18,
      integrity: 0.25,
      trust: 0.15,
    },
    shortName: "OST",
    startingCash: 0.2,
    weeklyStaffCap: 0.4,
    winProfile: "outsider",
  },
];

const legacyMedia: MediaOutlet[] = [
  {
    audienceMix: {
      conservativeMiddle: 0.3,
      securityHawks: 0.2,
      seniorSocial: 0.22,
    },
    credibility: 0.82,
    editorialVector: vec(0.05, 0.05, 0.05),
    id: "ct24",
    kind: "public_tv",
    name: "ČT24 Fórum",
    reach: 0.82,
    scrutiny: 0.72,
    sensationalism: 0.28,
  },
  {
    audienceMix: {
      liberalBusiness: 0.2,
      urbanProgressives: 0.26,
      youngRenters: 0.18,
    },
    credibility: 0.64,
    editorialVector: vec(-0.1, -0.35, -0.25),
    id: "metro",
    kind: "digital",
    name: "Metro Online",
    reach: 0.58,
    scrutiny: 0.42,
    sensationalism: 0.4,
  },
  {
    audienceMix: {
      industrialWorkers: 0.22,
      regionalPragmatists: 0.24,
      seniorSocial: 0.16,
    },
    credibility: 0.56,
    editorialVector: vec(-0.1, 0.2, 0.15),
    id: "region",
    kind: "regional",
    name: "Regionální síť",
    reach: 0.46,
    regionFocus: ["ustecky", "moravskoslezsky", "stredocesky"],
    scrutiny: 0.35,
    sensationalism: 0.32,
  },
  {
    audienceMix: {
      protestVoters: 0.28,
      securityHawks: 0.18,
      seniorSocial: 0.18,
    },
    credibility: 0.38,
    editorialVector: vec(-0.15, 0.45, 0.55),
    id: "blesk",
    kind: "tabloid",
    name: "Denní expres",
    reach: 0.62,
    scrutiny: 0.5,
    sensationalism: 0.82,
  },
];

void legacyMedia;

export const media: MediaOutlet[] = mediaOutlets;

export const sponsors: SponsorOffer[] = [
  {
    accepted: false,
    amount: 1.2,
    donorUnits: 1200,
    id: "members",
    kind: "membership_drive",
    legalStatus: "legal",
    name: "Členská sbírka",
    policyPressure: {},
    reputationRisk: 0,
    scandalRisk: 0.02,
    traceability: 0.95,
  },
  {
    accepted: false,
    amount: 2.4,
    donorUnits: 8,
    id: "builders",
    kind: "sector_network",
    legalStatus: "legal",
    name: "Svaz developerů",
    policyPressure: { housing: 0.45 },
    reputationRisk: 0.04,
    scandalRisk: 0.16,
    traceability: 0.82,
  },
  {
    accepted: false,
    amount: 2.1,
    donorUnits: 5,
    id: "regionalPatrons",
    kind: "regional_patron_network",
    legalStatus: "legal",
    name: "Regionální patroni",
    policyPressure: { transport: -0.25 },
    regionBonus: { stredocesky: 0.04, ustecky: 0.05 },
    reputationRisk: 0.05,
    scandalRisk: 0.2,
    traceability: 0.76,
  },
  {
    accepted: false,
    amount: 3.1,
    donorUnits: 4,
    id: "industry",
    kind: "sector_network",
    legalStatus: "legal",
    name: "Průmyslový fond",
    policyPressure: { climate: 0.35, industry: 0.35 },
    regionBonus: { moravskoslezsky: 0.06, ustecky: 0.04 },
    reputationRisk: 0.08,
    scandalRisk: 0.28,
    traceability: 0.72,
  },
  {
    accepted: false,
    amount: 2.8,
    donorUnits: 1,
    id: "bankLoan",
    kind: "bank_loan",
    legalStatus: "legal",
    name: "Bankovní úvěr",
    policyPressure: {},
    reputationRisk: 0.01,
    scandalRisk: 0.04,
    traceability: 0.98,
  },
  {
    accepted: false,
    amount: 1.8,
    donorUnits: 1,
    id: "thirdParty",
    kind: "registered_third_party",
    legalStatus: "gray",
    name: "Registrovaná třetí osoba",
    policyPressure: { security: 0.25 },
    reputationRisk: 0.06,
    scandalRisk: 0.22,
    traceability: 0.55,
  },
  {
    accepted: false,
    amount: 4.5,
    donorUnits: 1,
    id: "opaque",
    kind: "opaque_support",
    legalStatus: "illegal",
    name: "Neprůhledná podpora",
    policyPressure: { industry: 0.4, taxes: 0.25 },
    reputationRisk: 0.18,
    scandalRisk: 0.78,
    traceability: 0.3,
  },
];

export const events: EventCard[] = [
  {
    id: "healthcareStrike",
    issueAgendaShift: { healthcare: 0.24 },
    kind: "regional_crisis",
    opportunityFor: ["player", "kdu"],
    regionId: "ustecky",
    resolved: false,
    scope: "region",
    severity: 0.68,
    threatTo: ["ods"],
    title: "Stávková pohotovost v krajské nemocnici",
    week: 4,
  },
  {
    id: "housingReport",
    issueAgendaShift: { housing: 0.28 },
    kind: "policy_window",
    opportunityFor: ["player", "pirates"],
    regionId: "praha",
    resolved: false,
    scope: "region",
    severity: 0.72,
    title: "Nová data o nedostupném bydlení",
    week: 4,
  },
  {
    id: "industryLayoffs",
    issueAgendaShift: { industry: 0.3, security: 0.08 },
    kind: "macro",
    opportunityFor: ["player", "motorists"],
    regionId: "moravskoslezsky",
    resolved: false,
    scope: "region",
    severity: 0.66,
    threatTo: ["ods"],
    title: "Oznámené propouštění ve výrobě",
    week: 5,
  },
  {
    id: "schoolReform",
    issueAgendaShift: { education: 0.26 },
    kind: "policy_window",
    opportunityFor: ["stan", "pirates"],
    resolved: false,
    scope: "national",
    severity: 0.54,
    title: "Debata o reformě školství",
    week: 5,
  },
  {
    id: "securityIncident",
    issueAgendaShift: { security: 0.32 },
    kind: "macro",
    opportunityFor: ["ods", "spd"],
    resolved: false,
    scope: "national",
    severity: 0.62,
    title: "Bezpečnostní incident na hranicích",
    week: 6,
  },
  {
    id: "transportDelay",
    issueAgendaShift: { transport: 0.25 },
    kind: "regional_crisis",
    opportunityFor: ["stan", "player"],
    regionId: "stredocesky",
    resolved: false,
    scope: "region",
    severity: 0.58,
    title: "Zpožděná stavba železničního uzlu",
    week: 6,
  },
];

export const questions: QuestionSet[] = [
  {
    id: "schoolSun",
    prompt: "Student: Je Slunce planeta?",
    trigger: "school",
    options: [
      {
        consistencyValue: 0.6,
        controversyRisk: 0.02,
        factValue: 1,
        id: "a",
        reputationShift: { competence: 0.04, trust: 0.02 },
        rhetoricValue: 0.5,
        text: "Ne, Slunce je hvězda.",
      },
      {
        consistencyValue: -0.4,
        controversyRisk: 0.55,
        factValue: -0.8,
        id: "b",
        reputationShift: { competence: -0.12, controversy: 0.08 },
        rhetoricValue: 0.1,
        text: "Samozřejmě, je to největší planeta.",
      },
      {
        consistencyValue: 0.1,
        controversyRisk: 0.14,
        factValue: 0.2,
        id: "c",
        reputationShift: { authenticity: 0.03, competence: -0.03 },
        rhetoricValue: 0.62,
        text: "Tohle přenechám panu učiteli, já řeším rozpočet.",
      },
      {
        consistencyValue: 0.4,
        controversyRisk: 0.18,
        factValue: 0.4,
        id: "d",
        reputationShift: { trust: -0.01, authenticity: 0.02 },
        rhetoricValue: 0.76,
        text: "Důležité je, aby děti měly dobré školy.",
      },
    ],
  },
  {
    id: "housingInterview",
    prompt:
      "Moderátor: Jak zabráníte tomu, aby bytová politika jen zdražila nové byty?",
    trigger: "interview",
    options: [
      {
        consistencyValue: 0.72,
        controversyRisk: 0.08,
        factValue: 0.74,
        id: "a",
        issueOwnershipShift: { housing: 0.04 },
        reputationShift: { competence: 0.035 },
        rhetoricValue: 0.58,
        text: "Spojíme rychlejší povolování, podporu obcí a jasná pravidla pro dostupné byty.",
      },
      {
        consistencyValue: 0.35,
        controversyRisk: 0.18,
        factValue: 0.35,
        id: "b",
        reputationShift: { authenticity: 0.025, competence: -0.025 },
        rhetoricValue: 0.72,
        text: "Hlavně skončí chaos. Lidé potřebují slyšet, že stát nebude překážet.",
      },
      {
        consistencyValue: -0.15,
        controversyRisk: 0.35,
        factValue: 0.2,
        id: "c",
        reputationShift: { consistency: -0.04, controversy: 0.04 },
        rhetoricValue: 0.5,
        text: "Ceny prostě zastropujeme a trh se přizpůsobí.",
      },
    ],
  },
];

export const pollsters: Pollster[] = [
  {
    cost: 0.25,
    houseEffect: { ods: 0.002, player: -0.001 },
    id: "medianPlus",
    name: "Median Plus",
    quality: 0.76,
  },
  {
    cost: 0.18,
    houseEffect: { kdu: -0.002, pirates: 0.003 },
    id: "voxData",
    name: "VoxData",
    quality: 0.68,
  },
  {
    cost: 0.38,
    houseEffect: { player: 0.001, stan: -0.001 },
    id: "polisTrack",
    name: "Polis Track",
    quality: 0.84,
  },
];

export const marketingAdvisors: MarketingAdvisor[] = [
  {
    costPerWeek: 0,
    customActionUnlocks: false,
    id: "none",
    level: 0,
    messageTestingBonus: 0,
    name: "Bez externího týmu",
    predictionAccuracyBonus: 0,
    riskDetectionBonus: 0,
    segmentTargetingBonus: 0,
  },
  {
    costPerWeek: 0.35,
    customActionUnlocks: false,
    id: "junior",
    level: 1,
    messageTestingBonus: 0.02,
    name: "Junior analytický tým",
    predictionAccuracyBonus: 0.06,
    riskDetectionBonus: 0.04,
    segmentTargetingBonus: 0.03,
  },
  {
    costPerWeek: 0.8,
    customActionUnlocks: false,
    id: "senior",
    level: 2,
    messageTestingBonus: 0.07,
    name: "Senior strategie a data",
    predictionAccuracyBonus: 0.13,
    riskDetectionBonus: 0.1,
    segmentTargetingBonus: 0.09,
  },
  {
    costPerWeek: 1.5,
    customActionUnlocks: true,
    id: "elite",
    level: 3,
    messageTestingBonus: 0.14,
    name: "Elite war room",
    predictionAccuracyBonus: 0.22,
    reputationRisk: 0.03,
    riskDetectionBonus: 0.18,
    segmentTargetingBonus: 0.16,
  },
];

const legacyMediaInvitations: MediaInvitation[] = [
  {
    format: "interview",
    id: "metroHousing",
    issue: "housing",
    outletId: "metro",
    resolved: false,
    risk: 0.32,
    week: 4,
  },
  {
    format: "debate",
    id: "ctDebate",
    issue: "healthcare",
    outletId: "ct24",
    resolved: false,
    risk: 0.46,
    week: 4,
  },
  {
    format: "school",
    id: "schoolVisitInvite",
    issue: "education",
    outletId: "region",
    resolved: false,
    risk: 0.38,
    week: 5,
  },
];

void legacyMediaInvitations;

export const mediaInvitations: MediaInvitation[] = [];

export const coalitionRelations: CoalitionRelation[] = parties.flatMap(
  (partyA) =>
    parties
      .filter((partyB) => partyA.id < partyB.id)
      .map((partyB) => {
        const base =
          partyA.coalitionBase[partyB.id] ??
          partyB.coalitionBase[partyA.id] ??
          0.35;
        return {
          ideologicalCompatibility: base,
          partyA: partyA.id,
          partyB: partyB.id,
          personalTrust: base * 0.9,
          publicAcceptability: base,
          recentConflict: 0,
          scandalBarrier: 0,
          totalCoalitionPotential: base,
        };
      }),
);

export const defaultRules: GameRules = {
  donorCap: 3,
  finalWeek: 21,
  legalSpendCap: 40,
  spendCap: 90,
  thirdPartyCap: 1.8,
  totalWeeks: 20,
};

function inferSeedCenter8D(party: PartySeed): LatentVector8D {
  const field = party.field.center;
  const reputation = party.reputation;
  const climate = party.issuePositions.climate ?? 0;
  const security = party.issuePositions.security ?? 0;
  const industry = party.issuePositions.industry ?? 0;

  return latent8(
    field.econ,
    field.culture,
    field.authority,
    clampSeed(
      (reputation.trust + reputation.competence + reputation.integrity) / 1.55 -
        0.95 -
        reputation.controversy * 0.35,
    ),
    clampSeed(
      -field.culture * 0.45 -
        field.authority * 0.25 -
        security * 0.18 +
        industry * 0.08,
    ),
    clampSeed(-climate * 0.72 - industry * 0.08),
    clampSeed(
      -field.authority * 0.3 -
        field.culture * 0.16 +
        security * 0.28 +
        reputation.consistency * 0.12 -
        0.06,
    ),
  );
}

function inferSeedWidth8D(party: PartySeed): LatentVector8D {
  return latent8(
    party.field.width.econ,
    party.field.width.culture,
    party.field.width.authority,
    0.74,
    0.72,
    0.68,
    0.66,
  );
}

function clampSeed(value: number) {
  return Math.max(-1, Math.min(1, value));
}

const initialRuntime = (party: PartySeed): PartyRuntime => {
  const center8D = party.field.center8D ?? inferSeedCenter8D(party);
  const width8D = party.field.width8D ?? inferSeedWidth8D(party);
  const salience8D = party.field.salience8D ?? defaultSalience8D();

  return {
    actionCooldowns: {},
    cash: party.startingCash,
    field: {
      ...party.field,
      center: { ...party.field.center },
      center8D: { ...center8D },
      latentCenter: { ...center8D },
      originCenter: { ...party.field.originCenter },
      originCenter8D: { ...(party.field.originCenter8D ?? center8D) },
      salience8D: { ...salience8D },
      width: { ...party.field.width },
      width8D: { ...width8D },
    },
    graySpend: 0,
    informationQuality: party.id === "player" ? 0.42 : 0.32,
    leader: {
      energy: 1,
      fatigue: 0,
      officeRole: party.officeRole,
      timeCap: party.weeklyLeaderTimeCap ?? 3,
      timeUsed: 0,
    },
    legalExposure: 0,
    legalSpend: 0,
    marketingAdvisorId: "none",
    mediaVulnerability: 0,
    momentum: 0.5,
    organization: { ...party.organizationBase },
    parliamentAttendance: party.officeRole === "outsider" ? undefined : 1,
    reputation: { ...party.reputation },
    scandalRisk: party.reputation.controversy * 0.2,
    staffCap: party.weeklyStaffCap,
    staffUsed: 0,
    thirdPartySpend: 0,
  };
};

export type CreateInitialGameStateOptions = {
  baselineMode?: BaselineMode;
};

export function createInitialGameState(options: CreateInitialGameStateOptions = {}): GameState {
  const partyRuntime = Object.fromEntries(
    parties.map((party) => [party.id, initialRuntime(party)]),
  ) as Record<PartyId, PartyRuntime>;

  const initialState: GameState = {
    baselineCalibrated: false,
    baselineMode: options.baselineMode ?? DEFAULT_BASELINE_MODE,
    campaignActionsV2,
    coalitionRelations,
    events,
    grid: [],
    history: [],
    issueLayer: createIssueLayerState(),
    media,
    mediaAppearanceResults: [],
    mediaClusterModifiers: [],
    mediaInvitations,
    pendingMediaEffects: [],
    marketingAdvisors,
    mode: "fullRealism",
    nationalSupport: zeroPartyRecord(0),
    parties,
    partyRuntime,
    playerPartyId: "player",
    polls: zeroPollRecord(),
    pollsters,
    publicPollsterId: "medianPlus",
    publicRegionalPolls: {} as GameState["publicRegionalPolls"],
    questions,
    regions: regionSeeds,
    regionalSupport: {} as GameState["regionalSupport"],
    rngSeed: 42021,
    rules: defaultRules,
    scandals: [],
    segments: voterSegments,
    sponsors,
    turnoutModifiers: [],
    version: "0.5-campaign-actions-v2",
    week: 4,
  };

  initialState.mediaInvitations = generateWeeklyMediaInvitations(
    initialState,
    initialState.rngSeed,
  );
  return initialState;
}

export const segmentLabels: Record<SegmentId, string> = Object.fromEntries(
  voterSegments.map((segment) => [segment.id, segment.name]),
) as Record<SegmentId, string>;
