import { createVector8D, vector8D } from './dimensions';
import type { LatentVector8D, PartyField } from './types';

const center = (values: LatentVector8D) => createVector8D(values);

const width = (
  base: number,
  overrides: Partial<LatentVector8D> = {},
): LatentVector8D => ({
  ...vector8D(base),
  ...overrides,
});

const salience = (
  base: number,
  overrides: Partial<LatentVector8D> = {},
): LatentVector8D => ({
  ...vector8D(base),
  ...overrides,
});

export const partySeedsV03: PartyField[] = [
  {
    amplitude: 0.92,
    brandAwareness: 0.95,
    center: center({
      authority: 0.25,
      culture: 0.2,
      econ: -0.15,
      establishment: -0.25,
      globalism: -0.1,
      green: -0.15,
      ukraine: -0.2,
    }),
    consistency: 0.82,
    credibility: 0.78,
    id: 'ano',
    issuePositions: { greenDeal: { framingId: 'reformNotReject', position: -0.4, salience: 0.55 } },
    leaderEffect: 1.08,
    name: 'ANO',
    salience: salience(0.78, { establishment: 0.92 }),
    stigmaPenalty: 0.04,
    width: width(0.68, { culture: 0.78, establishment: 0.7, ukraine: 0.62 }),
  },
  {
    amplitude: 0.92,
    brandAwareness: 0.92,
    center: center({
      authority: 0.2,
      culture: 0.15,
      econ: 0.45,
      establishment: 0.55,
      globalism: 0.65,
      green: 0.05,
      ukraine: 0.7,
    }),
    consistency: 0.78,
    credibility: 0.82,
    id: 'spolu',
    issuePositions: { greenDeal: { framingId: 'modernization', position: 0.45, salience: 0.45 } },
    leaderEffect: 0.96,
    name: 'SPOLU',
    salience: salience(0.86, { econ: 1.05, globalism: 1.05, ukraine: 1.05 }),
    stigmaPenalty: 0.08,
    width: width(0.86, { culture: 0.92, green: 0.92 }),
  },
  {
    amplitude: 0.74,
    brandAwareness: 0.84,
    center: center({
      authority: -0.05,
      culture: -0.25,
      econ: 0.1,
      establishment: 0.6,
      globalism: 0.75,
      green: 0.35,
      ukraine: 0.75,
    }),
    consistency: 0.76,
    credibility: 0.8,
    id: 'stan',
    issuePositions: { greenDeal: { framingId: 'energySecurity', position: 0.75, salience: 0.6 } },
    leaderEffect: 0.98,
    name: 'STAN',
    salience: salience(0.86, { establishment: 1.04, globalism: 1.05, ukraine: 1.03 }),
    stigmaPenalty: 0.06,
    width: width(0.78, { culture: 0.86, econ: 0.9 }),
  },
  {
    amplitude: 0.98,
    brandAwareness: 0.82,
    center: center({
      authority: -0.45,
      culture: -0.65,
      econ: -0.15,
      establishment: 0.35,
      globalism: 0.7,
      green: 0.6,
      ukraine: 0.75,
    }),
    consistency: 0.74,
    credibility: 0.72,
    id: 'pirati',
    issuePositions: { greenDeal: { framingId: 'climateResponsibility', position: 1.45, salience: 0.78 } },
    leaderEffect: 0.94,
    name: 'Piráti',
    salience: salience(0.92, { culture: 1.18, green: 1.08 }),
    stigmaPenalty: 0.1,
    width: width(0.68, { econ: 0.82, globalism: 0.78, ukraine: 0.78 }),
  },
  {
    amplitude: 1.22,
    brandAwareness: 0.9,
    center: center({
      authority: 0.7,
      culture: 0.7,
      econ: -0.25,
      establishment: -0.8,
      globalism: -0.85,
      green: -0.45,
      ukraine: -0.85,
    }),
    consistency: 0.86,
    credibility: 0.58,
    id: 'spd',
    issuePositions: { greenDeal: { framingId: 'expensiveBureaucracy', position: -1.55, salience: 0.85 } },
    leaderEffect: 1.02,
    name: 'SPD',
    salience: salience(0.98, { establishment: 1.15, globalism: 1.16, ukraine: 1.18 }),
    stigmaPenalty: 0.12,
    width: width(0.66, { econ: 0.78 }),
  },
  {
    amplitude: 1.7,
    brandAwareness: 0.82,
    center: center({
      authority: 0.35,
      culture: 0.45,
      econ: 0.55,
      establishment: -0.35,
      globalism: -0.35,
      green: -0.65,
      ukraine: -0.25,
    }),
    consistency: 0.76,
    credibility: 0.56,
    id: 'motoriste',
    issuePositions: { greenDeal: { framingId: 'industrialThreat', position: -1.65, salience: 0.9 } },
    leaderEffect: 0.92,
    name: 'Motoristé',
    salience: salience(0.92, { econ: 1.08, green: 1.18 }),
    stigmaPenalty: 0.12,
    width: width(0.7, { econ: 0.76, green: 0.66 }),
  },
  {
    amplitude: 1.12,
    brandAwareness: 0.74,
    center: center({
      authority: 0.25,
      culture: 0.35,
      econ: -0.75,
      establishment: -0.75,
      globalism: -0.85,
      green: -0.25,
      ukraine: -0.9,
    }),
    consistency: 0.8,
    credibility: 0.54,
    id: 'stacilo',
    issuePositions: { greenDeal: { framingId: 'expensiveBureaucracy', position: -1.2, salience: 0.72 } },
    leaderEffect: 0.9,
    name: 'Stačilo',
    salience: salience(0.94, { econ: 1.12, establishment: 1.14, globalism: 1.12, ukraine: 1.18 }),
    stigmaPenalty: 0.18,
    width: width(0.66, { econ: 0.74, culture: 0.78 }),
  },
];

